### PR TITLE
update rewrite for published location

### PR DESCRIPTION
**Pull request by smrgeoinfo**
vocab going public

### CODE REVIEW

**Comment by smrgeoinfo** [comment]
the airo files are still causing weird problems

**Comment by dgarijo** [comment]
@smrgeoinfo what is the problem you face? Can't you pull the latest update and build from there?
I do not think the solution should be forcing everyone to ignore a vocabulary that you do not own. If the authors want to add changes to that folder it may be problematic.

**Comment by smrgeoinfo** [comment]
I sync'd my fork with master, and they didn't go away. I'll try a clean pull.

**Comment by dgarijo** [comment]
Thanks!

**Pull request closed without merging**
