### PR TITLE
/valueflows/ Add contact info & fix onto redirect

### PR DESCRIPTION
**Pull request by hoijui**

### CODE REVIEW

**Comment by davidlehn** [comment]
@ahdinosaur @djodjoni You two are the previous commiters to this file.  Is this ok?

@hoijui Please update the README with the github ids of the maintainers.

**Comment by fosterlynn** [comment]
Hi @davidlehn I'm actually the primary maintainer of Valueflows now.  @ahdinosaur or @djodjoni if you do see this, yes it is a needed change, and it would be great if you confirm that here.  I'll also ping them through other channels.

**Comment by hoijui** [comment]
Added the IDs

**Comment by ahdinosaur** [comment]
> `@ahdinosaur` `@djodjoni` You two are the previous commiters to this file. Is this ok?

@davidlehn hi yes this is okay!

**Pull request merged**
