### PR TITLE
fix punctuation and typo in README

### PR DESCRIPTION
**Pull request by TallTed**
@noelmcloughlin -- Please approve.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
Yes I approve. thank you. pls merge

**Comment by noelmcloughlin** [comment]
Would it be possible to update the commit message to remove my name. 
Otherwise I get pinged when people are working with the commits in their fork

image

**Comment by davidlehn** [comment]
@TallTed In the future please don't use messages like that in commit messages.  That title was fine by itself.

@noelmcloughlin Sorry I didn't notice that message before.  I just read the PR text.  How bad is this issue?  We'd have to edit the message and force push to master which would cause some havoc for everyone that has pulled that change in already.

**Comment by noelmcloughlin** [comment]
I just got pinged from someones branch, so email looks like a new zombie PR, I can live with this, probably get a few pings over time but can ignore it.   You could look at introducing CommitLint, maybe it can catch that, although 1st time I saw this issue.

**Pull request merged**
