### PR TITLE
Correctes rules in htaccess file

### PR DESCRIPTION
**Pull request by tanktoo**

### CODE REVIEW

**Comment by dgarijo** [comment]
@tanktoo,
You are creating the w3id: https://w3id.org/iot/fd/fd
Is this intended (note the double `fd`)?

**Comment by tanktoo** [comment]
Hm, for https://w3id.org/iot/qoi/ it is working with the same .htaccess file. Do I miss something here?

**Comment by dgarijo** [comment]
If you want https://w3id.org/iot/fd, you rewrite rule should be `RewriteRule ^$` instead of `RewriteRule ^fd$`. Note that you are already in the `fd` folder

**Comment by tanktoo** [comment]
Ok, did a new merge request. Closed this one. Thanks for help!

**Pull request closed without merging**
