### PR TITLE
Updated permalinks to different versions

### PR DESCRIPTION
**Pull request by HadleyKing**
Comment ID: 26444800023
Page: 2
Line: 16
Comment: Footnote 1/3-8 Wrong URLs https://www.w3id/biocompute/schemas/1.3.0/biocomputeobject.json
Must Be Satisfied: Yes
Change: permalinks are Registered and update footnotes will be added. Make hyperlinks.

https://w3id.org/biocompute/2791/description_domain.json
https://w3id.org/biocompute/2791/execution_domain.json
https://w3id.org/biocompute/2791/io_domain.json
https://w3id.org/biocompute/2791/parametric_domain.json
https://w3id.org/biocompute/2791/provenance_domain.json
https://w3id.org/biocompute/2791/usability_domain.json
https://w3id.org/biocompute/2791/

- https://gitlab.com/IEEE-SA/BioCompute/crg/bco-schema/issues/41

### CODE REVIEW

**Comment by davidlehn** [comment]
Please remove `.DS_Store` from the commit.  I just added it to the top-level `.gitignore` so hopefully that won't be a future issue.

**Comment by davidlehn** [comment]
I already added the ignore rule at the top level so you don't need another .gitignore file.  You could rebase your PR off of master to see the change.  Can you remove git new .gitignore file and the .DS_Store file from this PR?

**Comment by HadleyKing** [comment]
> I already added the ignore rule at the top level so you don't need another .gitignore file. You could rebase your PR off of master to see the change. Can you remove git new .gitignore file and the .DS_Store file from this PR?

Those files are no longer in my branch. Is that what you were asking for? Or should I do a rebase and recommit? 
Sorry for my confusion.

**Comment by davidlehn** [comment]
`.DS_Store` is still here: https://github.com/perma-id/w3id.org/pull/1445/files.  If you could at least remove that file, I can squash this PR.  Or you could squash the commits and force push.

**Pull request closed without merging**
