### PR TITLE
Hysope2 init

### PR DESCRIPTION
**Pull request by zawadzl**

### CODE REVIEW

**Comment by dgarijo** [comment]
@zawadzl,
there is no redirection. Can you please add one?

**Comment by zawadzl** [comment]
Sorry @dgarijo, we do not know the exact redirection URL just yet. Do you mind if we add this later this year ?
Or I can just add the file with a "random" URL and change it later. What do you prefer?

**Comment by dgarijo** [comment]
We do not accept reserving w3ids, so I would suggest that if you don't know it yet, then add a temporary URL that you can later change by another one.

**Comment by zawadzl** [comment]
OK I will, sorry about that!
Thanks

**Comment by zawadzl** [comment]
OK, done @dgarijo

**Pull request merged**
