### PR TITLE
Initial commit for /tern

### PR DESCRIPTION
**Pull request by edmondchuc**

### CODE REVIEW

**Comment by dgarijo** [comment]
@edmondchuc,
please note that this is not a repository for hosting files besides the redirections to your URLs. Please remove all the non .htaccess or readme files from the PR.

**Comment by edmondchuc** [comment]
@dgarijo I have removed all files except for the `.htaccess` and `README.md` as requested.

**Comment by dgarijo** [comment]
I recommend doing 303 redirections if you want to do content negotiation, instead of 302. See https://www.w3.org/TR/swbp-vocab-pub/#recipe3

**Comment by davidlehn** [comment]
@dgarijo It's better to get the unwanted files out of the commit history before merging.  Adding a removal commit will still leave those extra files here are in the history.

**Comment by edmondchuc** [comment]
Thanks for the tip @dgarijo. I've made another pull request using 303 redirects instead of 302 redirects. Cheers.

**Pull request merged**
