### PR TITLE
Update of .htaccess

### PR DESCRIPTION
**Pull request by anuzzolese**
This update of .htaccess enables the redirect to all subfolders of
scholarlydata.

### CODE REVIEW

**Comment by davidlehn** [comment]
Use this instead:
RewriteRule ^(.+)$ http://www.scholarlydata.org/$1 [R=302,L]

**Comment by anuzzolese** [comment]
@davidlehn you mean that rule as the only rewrite rule of the htaccess?

**Comment by davidlehn** [comment]
No, I meant just the additional rule.  You could combine both into just:
RewriteRule ^(.*)$ http://www.scholarlydata.org/$1 [R=302,L]

**Comment by AnLiGentile** [comment]
I changed it to the single rule
RewriteRule ^(.*)$ http://www.scholarlydata.org/$1 [R=302,L]

**Comment by davidlehn** [comment]
Done in #386

**Pull request closed without merging**
