### PR TITLE
Updating Redirects for IDSA and I40/STO*

### PR DESCRIPTION
**Pull request by sebbader**
We have reached significant progress in our IDSA and I40-related projects, which we need to reflect now in several adjustments to our redirect links.

idsa: new version of the vocabulary
sto: new version of the resource
sto_iot: new namespace used in the vocabulary, therefore another redirect is required.

### CODE REVIEW

**Comment by dgarijo** [comment]
@sebbader,
you are making significant edits to a w3id for which you are not listed as the contacts, and you are actually replacing them. Can I get a confirmation from them that they are ok with the change?
Also, in your w3id, why are you doing 301 instead of 303? It does not follow best practices: https://www.w3.org/TR/swbp-vocab-pub/ 

Thanks!

**Comment by sebbader** [comment]
Hello Daniel,
great to see that you guys pay so much attention! Sure, let me answer each of the points:
- Contacts: We had several changes regarding the people contributing to the two projects. I have asked the previous contributers, they will announce their permission in this thread.
- 301 vs 303: I will update the respective lines.
- Extension: We were able to move the STO documentation files from a private server to github pages. I will shortly update the respective sections and come back to you.

Best regards,
Sebastian Bader

**Comment by dgarijo** [comment]
@sebbader,
great, I will wait to hear from them before merging the PR.
Thanks!

**Comment by cmader** [comment]
Hi! Sebastian's changes regarding the authors are fine, thanks for checking and asking back! best regards, Christian

**Pull request merged**
