### PR TITLE
Creating cd2h new authority with an example redirect

### PR DESCRIPTION
**Pull request by cgcook**
Creating new authority for CD2H, htaccess.txt coming soon.

### CODE REVIEW

**Comment by davidlehn** [comment]
Please rename `htaccess.txt` to `.htaccess`.

**Comment by cgcook** [comment]
Thanks, I've updated it.

**Comment by jmcmurry** [comment]
Not sure why it is not working. Are hyphens not allowed?

**Comment by davidlehn** [comment]
Ah, can't have a space in the options. I made the quick fix for you:
https://github.com/perma-id/w3id.org/commit/458848a3bdd31492022fd00a5f520af2f19c8bdd

**Comment by jmcmurry** [comment]
Awesome! Thanks

**Pull request merged**
