### PR TITLE
persistent URIs for the BMO

### PR DESCRIPTION
**Pull request by JYL61**
I'd like to add the persistent URIs to the ontology.

### CODE REVIEW

**Comment by dgarijo** [comment]
@JYL61 please add your GitHub alias as part of the maintainer list, otherwise it's very difficult for us to do the connection. Thanks in advance

**Comment by giorgialodi** [comment]
Hi @dgarijo  ok I will!

**Comment by JYL61** [comment]
> @JYL61 please add your GitHub alias as part of the maintainer list, otherwise it's very difficult for us to do the connection. Thanks in advance

Ok. I have checked.  confirm "allow edits by maintainers", right?

**Comment by dgarijo** [comment]
@JYL61 please add your github id in the readme. At the moment you have:
```
Contacts
*yali Jiang <Jiangy61@cardiff.ac.uk>
```
What I am asking for is:
```
Contacts
*yali Jiang <Jiangy61@cardiff.ac.uk>, @JYL61 
```
Thanks

**Comment by JYL61** [comment]
@dgarijo many thanks. it is done.

**Pull request merged**
