### PR TITLE
htaccess file for ontology: Quality Ontology for IoT Data Sources

### PR DESCRIPTION
**Pull request by tanktoo**

### CODE REVIEW

**Comment by tanktoo** [comment]
redirection files for Quality Ontology for IoT Data Sources

**Comment by dgarijo** [comment]
@tanktoo,
you seem to be redirecting to ^coil instead to ^qoi

**Comment by tanktoo** [comment]
Hi @dgarijo,
thanks for the proof check. I have corrected it.

**Comment by dgarijo** [comment]
;)

**Pull request merged**
