### PR TITLE
Add people/nick

### PR DESCRIPTION
**Pull request by nickandrew**
Add the standard `.htaccess` file to enable people/nick.

### CODE REVIEW

**Comment by msporny** [comment]
@nickandrew - see this thread before we pull - https://github.com/perma-id/w3id.org/pull/211

**Comment by nickandrew** [comment]
Ok, redoing it per #211.

**Comment by msporny** [comment]
Thanks, also as a side question - how did you hear about w3id.org? We've had a flood of requests tonight and we're trying to figure out if it was because of some story or blog post.

**Comment by nickandrew** [comment]
It was mentioned on the twitters.

**Pull request closed without merging**
