### PR TITLE
.htaccess

### PR DESCRIPTION
**Pull request by priyankadank**
I need to create URL for http://52.39.181.105:8082/resa where the application sentitrack is running.

### CODE REVIEW

**Comment by priyankadank** [comment]
Please let me know why the commit from my side  failed

**Comment by davidlehn** [comment]
Ignore the travis check, it's failing for other reasons.

Can you please squash the commits into one?

Also perhaps add a README or comments to the .htaccess with some contact info.  Thanks.

I can't connect to that IP/port.  Is this redirect something you intend to be using for a long time?

**Comment by priyankadank** [comment]
I have now squashed the commits. You can connect to the IP now (http://52.39.181.105:8082/resa).
We want to use the redirect for long time.

**Comment by davidlehn** [comment]
That didn't squash the commits in this PR.  And there's a new rebase temporary .txt file added.

**Comment by priyankadank** [comment]
Hi,

Sorry, the commands were not squashed earlier. But I guess, those are squashed now.

**Pull request merged**
