### PR TITLE
added a new maintainer

### PR DESCRIPTION
**Pull request by beyzayaman**
I am a new maintainer of the ontology so I added myself as a new maintainer.

### CODE REVIEW

**Comment by dgarijo** [comment]
@beyzayaman, can you please ask kris.mcglinn@adaptcentre.ie for their approval on this pull request?
Otherwise, you cannot add yourself as a maintainer for someone else's w3id :)

**Comment by beyzayaman** [comment]
sure :)

**Comment by davidlehn** [comment]
You should add a `.htaccess` for the `fairvasc-fdp` directory too.  Ideally you should do different PRs for different directories, just to make changes easier to follow.  Note that these redirects are case sensitive.  You've got a mix of upper and lower case, but if that works for your use case, that's fine.

**Comment by beyzayaman** [comment]
Hi @davidlehn. We have a mix of the upper and lower case due to having different maintainers so it is working for us so far and we'll keep it this way. Thanks for pointing that out. I also added `.htaccess`.

@dgarijo @kmcglinn sent a mail some time ago to approve the maintainers' change. Can you please check that and approve if this is working for you?

**Comment by dgarijo** [comment]
@beyzayaman, sorry but I have not received an email. Would it be possible to have the public acceptance here?

**Comment by davidlehn** [comment]
@beyzayaman I only see `fairvasc-fdp/readme.md` in this PR, did you forget to push the `.htaccess`?

**Comment by beyzayaman** [comment]
> @beyzayaman I only see `fairvasc-fdp/readme.md` in this PR, did you forget to push the `.htaccess`?

It seems so. Is it ok now?

**Pull request merged**
