### PR TITLE
add toco ontology

### PR DESCRIPTION
**Pull request by QianruZhou333**
a new ontology for networks redirection request submitted.

### CODE REVIEW

**Comment by davidlehn** [comment]
It looks like you added similar content in 3 places and added some submodule thing?  Please at least squash this down to just one commit and remove duplicate files as needed.

**Comment by dgarijo** [comment]
Also, be aware that you seem to want to create a w3id for: https://w3id.org/toucan_ontology/
However, you are creating the following one: https://w3id.org/cbv/toco/toco

**Comment by QianruZhou333** [comment]
Thank you for your comments. I have get rid of duplicate ones, and leave only "toco/*". The url I want to create is https://w3id.org/toco/toco . Is that possible that you could check and advise? Thank you.

**Comment by davidlehn** [comment]
Can you fix the removal of the `cbv/.htaccess` file?  Also you should squash all these commits into one and force push to your branch.

**Comment by QianruZhou333** [comment]
The local repository in my computer has been removed, thus I cannot squash the previous commits anymore. Sorry about that.

**Comment by davidlehn** [comment]
- There's an extra line added in cbv/.htaccess.
- There's a copy of the .htaccess called htaccess.
- There's still sub submodule thing listed in the changes.
- You could check out your branch, fix things, squash the commits, and force push.

**Comment by QianruZhou333** [comment]
sorry for the inconvenience, I think it is more convenient to reform the repository and made a new pull request. Is that possible that you could delete this pull request? Thank you very much.

**Comment by davidlehn** [comment]
Moved to: https://github.com/perma-id/w3id.org/pull/899

**Pull request closed without merging**
