### PR TITLE
 Publish an ontology - Permanent identifier

### PR DESCRIPTION
**Pull request by fortiss-itsm**
Permanent identifier for ontology publication. 
Would you please create a persistent URL for this ontology?

Best Regards,
Matthias

### CODE REVIEW

**Comment by fortiss-itsm** [comment]
README.md updated

**Comment by dgarijo** [comment]
@fortiss-itsm http://213.136.65.6:8080 doesn't look like a stable URL. Can you please place your resources somewhere else? Github is a possibility...

**Comment by davidlehn** [comment]
Also please squash your PR into one commit.

**Comment by fortiss-itsm** [comment]
@dgarijo thank you very much for your feedback. I changed the URL and also squash my pr into one commit @davidlehn

**Comment by dgarijo** [comment]
@fortiss-itsm you seem to want to publish the ontology according to the W3C best practices (www.w3.org/TR/swbp-vocab-pub/). However, you are not doing content negotiation correctly (you only add a 302 redirection, instead of a 303).  
If you want a reference of how this can be done, you can look at this vocabulary: https://github.com/perma-id/w3id.org/blob/master/games/spec/.htaccess.

If you don't want to enable content negotiation, please confirm and I will merge the pull request as it is.

**Comment by fortiss-itsm** [comment]
@dgarijo I apologize for the inconvenience. At the moment i am fine without no content negotiation, so you can merge the pull reguest as it is. thank you very much for your x check

**Pull request merged**
