### PR TITLE
add @turbomam as gensc maintainer

### LINKED ISSUE #4016: add @turbomam as maintainer of `gensc` namespace

### PR DESCRIPTION
**Pull request by turbomam**
also fix spelling of Ramona's name and add her GH handle

requires approval from @ramonawalls 

closes #4016

### CODE REVIEW

**Comment by dgarijo** [comment]
@ramonawalls ping

**Comment by davidlehn** [comment]
- @turbomam: This may need a rebase.
- @ramonawalls: This is still waiting for approval. (And changes already happened in https://github.com/perma-id/w3id.org/pull/4003)

**Comment by ramonawalls** [comment]
Thank you both for the changes, and for the ping, @davidlehn. Let me see if I can resolve the conflicts.

**Comment by ramonawalls** [comment]
Resolved conflict. I approve the merge.

**Pull request merged**
