### PR TITLE
update links of semsur, seo and eventskg

### PR DESCRIPTION
**Pull request by saidfathalla**
due to server updates, all links of these ontologies are updated.

### CODE REVIEW

**Comment by dgarijo** [comment]
@saidfathalla,
you are trying to modify w3ids for which you are not listed as the owner.
In particular, for EVENTSKG you have not committed the original push. We need the ok from @Hebaallahibrahim.
Also, please add yourself as a maintainer in case future changes are required. Thanks!!

**Comment by Hebaallahibrahim** [comment]
its ok for me. We both are the maintainer of EVENTSKG.

**Comment by dgarijo** [comment]
Then please add in the readme file the full maintainer list. Thanks!

**Comment by Hebaallahibrahim** [comment]
done in #2427

**Pull request merged**
