### PR TITLE
Create .htaccess

### PR DESCRIPTION
**Pull request by marianofl1971**
This address is for top-level (upper-level, general) ontologies.

### CODE REVIEW

**Comment by dgarijo** [comment]
@marianofl1971 
please add a readme file stating the maintainer and a brief description of the project.
Thanks in advance

**Comment by davidlehn** [comment]
In your .owl file on your server you should also change http://w3id.org/* to https://w3id.org/* to avoid the extra redirect that w3id will otherwise always do.

**Comment by marianofl1971** [comment]
I have already changed the IRI of the ontology, and I have carried out a
pull request with a readme file.

There is no problem if I have to do something more.

Thanks a lot for your help.

Mariano

2017-05-05 18:09 GMT+02:00 Daniel Garijo <notifications@github.com>:

**Comment by dgarijo** [comment]
@marianofl1971,
now you have 2 PRs open. Could you please close one of them and submit the changes in a single one?

**Pull request closed without merging**
