### PR TITLE
Adding a w3id pid to the dcso ontology

### PR DESCRIPTION
**Pull request by JoaoMFCardoso**
Hi.

I'm a relative newbie to this. I was told to resort to the w3id to get a persistent identifier for the ontology that I've been working on.

I've changed the namespace in the ontology to https://w3id.org/dcso#

I've tried to do my best to create a .htaccess file that points to the github location of the latest .owl file.

I've also added the version of the ontology as an annotation to the .owl file.

Any help spoting potential errors is much appreciated. As well as an approval of the pull request :)

Best,
JC

### CODE REVIEW

**Comment by dgarijo** [comment]
@JoaoMFCardoso, a few points:

1) Your namespace has an "aco" at the end of your w3ids, so you are reserving https://w3id.org/dcso/aco instead of https://w3id.org/dcso. In order to fix that you have to change the rewrite rule:
`RewriteRule ^aco$` to be `RewriteRule ^$`
1)  You are providing github urls, they won't load from protege. You should create a github page or copy the content of the url instead

**Comment by JoaoMFCardoso** [comment]
> @JoaoMFCardoso, a few points:
> 
> 1. Your namespace has an "aco" at the end of your w3ids, so you are reserving https://w3id.org/dcso/aco instead of https://w3id.org/dcso. In order to fix that you have to change the rewrite rule:
>    `RewriteRule ^aco$` to be `RewriteRule ^$`
Rookie mistake. Just fixed it.

> 2. You are providing github urls, they won't load from protege. You should create a github page or copy the content of the url instead

Added the link to the raw version of the .owl file. I guess this solves the issue.

**Comment by JoaoMFCardoso** [comment]
Should I do a new pull request? Or commiting the changes is enough?

**Comment by dgarijo** [comment]
Just committing the new changes should update your PR.

**Comment by dgarijo** [comment]
I just noticed one thing: In the HTML redirection, you are redirecting to the OWL ontology, which is incorrect. You should redirect to an html page. The redirection will work, it's just not serving the content properly

**Pull request merged**
