### PR TITLE
IMGpedia permanent URL request

### PR DESCRIPTION
**Pull request by scferrada**

### CODE REVIEW

**Comment by davidlehn** [comment]
Is this supposed to be updating the UN/ rules too?

**Comment by scferrada** [comment]
No, I'm not sure what happened there. I didn't change anything there. May I amend the commit?

**Comment by davidlehn** [comment]
Please do.  Ideally just edit the current commit and force push it to your branch.  Otherwise, please add another commit to revert the unwanted changes.

**Comment by scferrada** [comment]
I think it's done now. Thanks for the time, David.

**Pull request merged**
