### PR TITLE
addind SemSur ontology

### PR DESCRIPTION
**Pull request by saidfathalla**
this is a core ontology for semantic surveys

### CODE REVIEW

**Comment by saidfathalla** [comment]
All checks have failed... why?

**Comment by davidlehn** [comment]
> All checks have failed... why?

A link checker is run on the whole system, and it fails for other stuff.  Just ignore it.

**Comment by davidlehn** [comment]
- w3id is intended to provide links that redirect to resources hosted on other sites.  Please remove the html and owl files from the commit and host them elsewhere.
- The .htaccess file is full of errors.  Slashes and maybe other content seem to be missing all over.
- Looks like another .htaccess file was copied but the old comments remain.  Update them.
- The redirs to github.com will load up the github ui for a file.  You probably mean to redir to a raw resource.

**Comment by davidlehn** [comment]
Also please add contact info to the README.  Thanks.

**Comment by dgarijo** [comment]
Also, you seem to be adding a redirection to w3id.org/SemSur/semsur. I think you might be interested in only having 1 "SemSur" in your URI

**Comment by davidlehn** [comment]
Is this PR still needed or can it be closed?

**Comment by davidlehn** [comment]
No response, closing.  Reopen and make requested changes if needed.

**Pull request closed without merging**
