### PR TITLE
Update .htaccess

### PR DESCRIPTION
**Pull request by jhaag75**
Rewrite rule for xml vocabulary

### CODE REVIEW

**Comment by davidlehn** [comment]
Can you please squash this into one commit?  Thanks.

**Comment by jhaag75** [comment]
Hi David,

Is there a quick and easy way of doing this? Can I create a new fork of the
current w3id repository and then submit a new pull request? Appreciate any
advice.

Regards,

J Haag

-------------------------------------------------------
+1.850.266.7100(office)
+1.850.471.1300 (mobile)
jhaag75 (skype)
http://jasonhaag.com (Web)
http://twitter.com/mobilejson (Twitter)
http://linkedin.com/in/jasonhaag (LinkedIn)

**Comment by davidlehn** [comment]
The usual way is to rebase your branch then force push it.  A search for "github squash pull request" has many results, such as:
https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by jhaag75** [comment]
Thanks David. I just performed those steps here: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

Does this force update this pull request or should I do I need to submit a new now?

**Comment by davidlehn** [comment]
The force will update the PR.  I see you have 3 files changed now vs what was just 1 combined change before.  Is the PR correct now?

**Comment by jhaag75** [comment]
ok good, I see that it is one commit now "jhaag75  wants to merge 1 commit into perma-id:master from jhaag75:master"

Yes, that's fine the PR is correct now.

**Pull request merged**
