### PR TITLE
Mare project

### PR DESCRIPTION
**Pull request by diegoref**
This fork is required for a EU project we are involved within the fishery domain

### CODE REVIEW

**Comment by msporny** [comment]
Squash this changeset please, commit cba5 is unnecessary.

**Comment by diegoref** [comment]
Sorry, not clear what I should do. Could you please be more specific?

**Comment by dlongley** [comment]
@diegoref,

To "squash" your commits is to convert them into a single commit. This helps keep the git history clean; there's really only one change happening here, not three (and two of those changes just undo each other). For help on how to do this, see:

http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by diegoref** [comment]
I think I did it.... didn't I?
I downloaded the repository using GIT, then I typed
git reset --soft HEAD~3
git merge --squash
git commit
I am totally new to git so please advise me if I did wrong or what I should do....

**Comment by dlongley** [comment]
Make sure you force push your changes to your fork: `git push -f`

**Comment by diegoref** [comment]
ok I deleted my local folders...
Could you please tell me the steps I need to do starting from scratch? I mean, I have a terminal open and need to download the repository and squash the commits.

**Comment by dlongley** [comment]
On a freshly-cloned version of your fork do this:

```
git reset HEAD~3
git add mare
git commit -m "Add mare redirection."
git push -f
```

**Comment by diegoref** [comment]
thanks! did it!

**Comment by msporny** [comment]
Merged, thanks.

**Pull request merged**
