### PR TITLE
people\sergio: Web Resource for [Sergio J. Rodríguez M.]

### PR DESCRIPTION
**Pull request by srodriguez142857**
Please note that I only want to add a subfloder plus an .htaccess file on "people".

The SHA of the commit is:
0da1ec058c71ade33778d9b13b57ad460905cd09

For some reason, when I refreshed my local copy it did a complete merge. Please ignore that operation. Thank you.

### CODE REVIEW

**Comment by dgarijo** [comment]
I cannot merge this PR because it has conflicts with the main branch. Please update your repo and then submit a pr with your changes

**Comment by srodriguez142857** [comment]
Hi.

I've recreated my repo from scratch.
I've created a new branch where I've committed the changes that I want to
submit.
However, it's always failing whenever I'm trying to create a PR:

Into which branch should I send the pull request?...
I'm sending the PR to the default one (master).

Thank you very much for your attention and assistance.
Looking forward to your reply.

/$¡rm
Best regards,
Sergio Rodríguez.

**Comment by dgarijo** [comment]
Normally I don't create a new branch. I fork the main project, do my changes, issue a pull request against this PR and that's it.

**Comment by srodriguez142857** [comment]
Hi, Daniel.

Thank you very much for your insight.
I cloned again the local copy of my fork from perma-id/master.
I ran some git commands to sync my fork and check the updates.
Everything is OK now. I've made a successfully PR.

Appreciate your attention and assistance.

/$¡rm
Best regards,
Sergio Rodríguez.

**Pull request closed without merging**
