### PR TITLE
add versioned IRIs to DPV + new extensions

### PR DESCRIPTION
**Pull request by besteves4**

### CODE REVIEW

**Comment by dgarijo** [comment]
@besteves4 you are not listed as a maintainer of this w3id.
Please have Harshvardhan J. Pandit approve this PR

**Comment by coolharsh55** [comment]
Hi @dgarijo - thanks for checking. Yes beatriz's PR is from us / DPVCG. @besteves4 should we add you as the maintainer for w3id as well?

**Comment by besteves4** [comment]
Sure, that works!

**Comment by coolharsh55** [comment]
@besteves4 great, then let's amend the PR and add your name to the files

**Comment by besteves4** [comment]
@dgarijo @coolharsh55 updated the PR with my details

**Pull request merged**
