### PR TITLE
Started to integrate widoco based documentation

### PR DESCRIPTION
**Pull request by GeorgFerdinandSchneider**
added new files accordingly and revised htacces file

### CODE REVIEW

**Comment by dgarijo** [comment]
You are not serving the html properly (see https://raw.githubusercontent.com/TechnicalBuildingSystems/Ontologies/master/CTRLont/index-en.html or https://htmlpreview.github.io/?https://raw.githubusercontent.com/TechnicalBuildingSystems/Ontologies/master/StateMachineOntology/StateMachineOntology.html, you don't have any styles). I recommend using a github page instead.

**Comment by GeorgFerdinandSchneider** [comment]
@dgarijo Thanks for your comment. We changed accordingly [https://technicalbuildingsystems.github.io/Ontologies/](https://technicalbuildingsystems.github.io/Ontologies/)

We hope this now serves the html properly any further corrections are highly welcome. We are working on introducing widoco based documentation also for the other ontologies. 

Best

Georg

**Comment by dgarijo** [comment]
@GeorgFerdinandSchneider,
in line 20, why do you add a 302 to the HTML? Wouldn't it have to be a 303 (see other)?

**Comment by dgarijo** [comment]
The same in line 27-28for the rdf xml serialization.

**Comment by dgarijo** [comment]
@GeorgFerdinandSchneider,
any comments on my questions?
thanks

**Comment by GeorgFerdinandSchneider** [comment]
@dgarijo apologies for the delay. I corrected the redirect to a 303.

Best

**Pull request merged**
