### PR TITLE
Update .htaccess

### PR DESCRIPTION
**Pull request by tudorliv**
HI! 
Can you help me, please ... I want to rename the branch "iot-tta" to "iiot" (with 2 "i"). 
Instead https://w3id.org/iot-tta  to be https://w3id.org/IIoT
Thank you!
Liviana Tudor

### CODE REVIEW

**Comment by davidlehn** [comment]
- To make a name, you can change the directory name.  Are you able to do that or are you requesting someone else make a PR?
- You say you want "iiot" but also "https://w3id.org/IIoT".  The urls are case sensitive, you need to choose one.
- The old and new URLs in this PR appear to return 404.  Are they correct?

**Comment by tudorliv** [comment]
Hi,
It is OK IIoT. 
Thank you,
Liviana Tudor

**Comment by tudorliv** [comment]
Hi,

It

În vin., 26 iul. 2024 la 01:14, David I. Lehn ***@***.***> a
scris:

**Comment by tudorliv** [comment]
Hi,

It is correct: https://tudorliv.github.io/IIoT/IIoT.owl, but I see that it
doesn't work with this link.
Maybe this link:
https://github.com/tudorliv/IIoT/blob/main/IIoT.owl   ???
Thank you,
Liviana Tudor

În vin., 26 iul. 2024 la 18:44, Liviana Tudor ***@***.***> a
scris:

**Comment by davidlehn** [comment]
Update complete in other PRs.  Move done in https://github.com/perma-id/w3id.org/pull/4313.  Closing.

**Pull request closed without merging**
