### PR TITLE
yarrrml: add target screencast redirect

### PR DESCRIPTION
**Pull request by DylanVanAssche**
- Fix redirect for original screencast
- Add redirect for target screencast
- Add myself as maintainer

### CODE REVIEW

**Comment by dgarijo** [comment]
@DylanVanAssche,
you are trying to modify a w3id in which you are not listed as a maintainer.
Please have your PR approved by  Pieter Heyvaert pheyvaer.heyvaert@ugent.be,  Ben De Meester ben.demeester@ugent.be or    Anastasia Dimou anastasia.dimou@ugent.be.

**Comment by dgarijo** [comment]
@DylanVanAssche,
sorry, you still need approval from any of the previous maintainers to become a maintainer yourself.

**Comment by DylanVanAssche** [comment]
@dgarijo Yes, I asked them :) They will comment here soon ;)

**Comment by pheyvaer** [comment]
LGTM!

**Pull request merged**
