### PR TITLE
try to solve urlencoding problem

### PR DESCRIPTION
**Pull request by smrgeoinfo**
the rewrite rule has an httpURI in the query value and the target server requires these to be URL encode, but when the rewrite happens, all the #n encodings in the URI are ignored.  Try fix based on github  #2846.  
see also #2853 

will this work?

### CODE REVIEW

**Comment by davidlehn** [comment]
I don't think that's option is currently enabled.  What's an example URL and the resulting redirect you want?

**Comment by smrgeoinfo** [comment]
input url:
http://w3id.org/geochem/1.0/analyticalmethod/particleinducedxrayspectrometry

rule:
RewriteRule    ^analyticalmethod/([A-Za-z_]+)$     https://demo.vocabs.ardc.edu.au/repository/api/lda/earthchem-georoc/analytical-methods-for-geochemistry/0-1/resource?uri=http%3A%2F%2Fw3id.org%2Fogeochem%2Fdef%2F1%2Fanalyticalmethod%2Fmethod%2F$1  [R=303,L]

rewrite should be:
https://demo.vocabs.ardc.edu.au/repository/api/lda/earthchem-georoc/analytical-methods-for-geochemistry/0-1/resource?uri=http%3A%2F%2Fw3id.org%2Fogeochem%2Fdef%2F1%2Fanalyticalmethod%2Fmethod%2Fparticleinducedxrayspectrometry


what is the result query uri to https://demo.vocabs.ardc.edu.au/:
httpAFFw3id.orgFogeochemFdefF1FanalyticalmethodFmethodFparticleinducedxrayspectrometry

**Comment by smrgeoinfo** [comment]
add 'NE' in redirect paramters, per suggeston from Nick Car

**Comment by smrgeoinfo** [comment]
this is ready to pull...

**Comment by davidlehn** [comment]
This won't work.  "AllowEncodedSlashes" is not allowed in htaccess files and the server will just log errors and return a 500 error.

**Comment by smrgeoinfo** [comment]
Yup, that's what happens. Back to the drawing board...

**Comment by smrgeoinfo** [comment]
I tried without the allowEncodedSlashes, and added the [R=303,L,NE]  and get the same bad result-- the URL encoding gets smashed. Error is ```
That shortname is unrecognised.
unrecognised short name or literal: httpAFFw3id.orgFogeochemFdefF1FanalyticalmethodFmethodFbroadbeamxrayspectrometry
```
the 'F's should all be '%2F' and the 'A' '%3A'

**Pull request merged**
