### PR TITLE
Foaf file moved /people/michael

### PR DESCRIPTION
**Pull request by carducci**
Updating .htaccess to point to a new location for /people/michael

### CODE REVIEW

**Comment by dgarijo** [comment]
@carducci, do you mind pasting the original commit where you minted the w3id originally? I don't know if you are the same Michael or not :(

**Comment by TallTed** [comment]
@dgarijo — Original commit [adding people/michael](https://github.com/perma-id/w3id.org/commit/e62f10e7884e41a0e1a4b85504791425a7e254f1) was by @carducci.

**Comment by dgarijo** [comment]
Thanks @TallTed !

**Comment by carducci** [comment]
Y'all beat me to it! Thanks @TallTed! 

In future, I'll reference previous PR and commit. I apologize for the omission this time.

**Pull request merged**
