### PR TITLE
permanent urls for games

### PR DESCRIPTION
**Pull request by dgarijo**
Added 3 permanent urls for three game applications.

### CODE REVIEW

**Comment by dgarijo** [comment]
I don't understand why the build failed. All my links seem to be ok (they are simple 302 redirections), and the error it shows seems to be on the "rdw" repository . Can someone help me here?

**Comment by davidlehn** [comment]
The failure is due to the link checker checking links for every project.  An unrelated redriect is returning 503 which will cause every commit check to fail now.  Don't worry about it.

Why are you using IPs in the URLs vs host names?  That seems like a fragile setup compared to using the DNS system.

**Comment by dgarijo** [comment]
Thanks for your response!
Unfortunately I did not set those IPs and I have to live with them, but I will contact the responsible asap. As soon as I get new URLs, I will change them.

**Comment by davidlehn** [comment]
Ok.  If possible please keep resources on something that is somewhat stable to avoid the need for frequent w3id updates.  Thanks.

**Pull request merged**
