### PR TITLE
links to clipc documents

### PR DESCRIPTION
**Pull request by martinjuckes**

### CODE REVIEW

**Comment by martinjuckes** [comment]
Sorry, this was meant to be for the contents of the clipc directory only

**Comment by dgarijo** [comment]
The first link (http://www.clipc.eu/media/clipc/org/documents/Reports\ to\ REA/clipc_rp1_interimreview_addendum_final.pdf) does not work. Can you please fix it? Also, it is recommendable to add a readme file with a small description of the repository and who the main maintainer is, as well as where the links should point to ideally.

**Comment by martinjuckes** [comment]
Sorry about the bad link .. I've fixed that now, and added README.md files in the _docs_ and _proc_ directories. Contact details are in the top level README.md, which I have also improved a little.  Is this OK now?

**Comment by dgarijo** [comment]
it seems to be ok now.

**Pull request merged**
