### PR TITLE
Plan Executions (PlEx) Ontology

### PR DESCRIPTION
**Pull request by jonimoreira**
FAIR Workflows 
Profile reusing predicates from workflow ontologies.

### CODE REVIEW

**Comment by dgarijo** [comment]
@jonimoreira,
we don't store content files here. Instead, you should add the redirection to the server/repository with the right file. Please find some examples in the rest of the folders. For example:  https://github.com/perma-id/w3id.org/blob/master/ac-ontology/.htaccess

**Comment by jonimoreira** [comment]
Hi @dgarijo ,
Sorry for the mistake and thanks for the support. 
Can you check now if everything is ok, please? 
Thank you.

**Comment by dgarijo** [comment]
@jonimoreira,
is the w3id you want  https://w3id.org/fair/plex/aco ?? (Maybe the "aco" is a mistake??)

**Comment by jonimoreira** [comment]
It was a mistake, removed. Thnks

**Comment by dgarijo** [comment]
@jonimoreira,
now you have set it up to be  https://w3id.org/fair/plex/plex

**Pull request merged**
