### PR TITLE
FAIROS API service id

### PR DESCRIPTION
**Pull request by esgg**
Addition of the API description in swagger of the FAIROS service to assess the FAIRness of research objects

### CODE REVIEW

**Comment by esgg** [comment]
Generation of persistent identifier for the description of FAIROS

**Comment by esgg** [comment]
Github user: esgg

**Comment by dgarijo** [comment]
@esgg you have closed the pull request. Don't you want us to merge it?

**Comment by dgarijo** [comment]
Please add your github user in the readme file of your w3id. Otherwise it's difficult to map `esgg` to `Esteban García`
Thanks

**Comment by esgg** [comment]
Done

**Comment by dgarijo** [comment]
Please move fairos/api/README to /fairos and add your github user id there too

**Pull request merged**
