### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nfsec**
Too big SPAM source.

### CODE REVIEW

**Comment by davidlehn** [comment]
Spam is unstoppable. Hiding emails won't help. ;-)

Can you update this to list github ids (like @nfsec) that maintain the files?  Helps us track who is allowed to make updates.

**Comment by nfsec** [comment]
It can help for new scrapers.

You can always check the history of the file: https://github.com/perma-id/w3id.org/commits/0781f194e316909c86012d4a5399d16705327ced/nfsec/README.md

**Comment by davidlehn** [comment]
Sure we can look at history, but it's useful to have it explicitly mentioned somewhere since we check these things by hand.  Simple text like `"Maintainer: @nfsec"` is all we're asking for.

**Comment by nfsec** [comment]
OK no problem I understand. Please merge this PR, and I will create another with "Maintainer" info.

**Pull request merged**
