### PR TITLE
list v3 alpha blockcerts

### PR DESCRIPTION
**Pull request by lemoustachiste**
as per https://github.com/w3c-ccg/security-vocab/pull/66#discussion_r505589492

### CODE REVIEW

**Comment by dgarijo** [comment]
@lemoustachiste,
you are trying to modify a w3id for which you are not a maintainer. I see the latest edit was done by @lparkerlm, so it would be great if he could verify this commit. Also, please add yourself as a maintainer for the future.

**Comment by lemoustachiste** [comment]
Hi @dgarijo,

thanks for your feedback. Sorry if I missed that, but how do add myself as a maintainer?

**Review by lparkerlm — APPROVED** [review]
This looks good to me.

**Comment by dgarijo** [comment]
@lemoustachiste 
No worries; in the readme file, in Contacts, add you name/github id.
Thanks

**Comment by lemoustachiste** [comment]
@dgarijo added @lparkerlm and myself as maintainers

**Pull request merged**
