### PR TITLE
Add redirect for portal.aws.biochemistry.gwu.edu

### PR DESCRIPTION
**Pull request by HadleyKing**
Changes to be committed:
	modified:   .htaccess
	modified:   readme.md

### CODE REVIEW

**Comment by dgarijo** [comment]
@HadleyKing, you are trying to modify a w3id for which you are not listed as a maintainer. Right now I see listed:
* Raja Mazumder <mazumder@gwu.edu>
* Vahan Simonyan <vahansim@gmail.com>

Can you please contact them so the acknowledge this change is legit?
Thanks!

**Comment by HadleyKing** [comment]
> @HadleyKing, you are trying to modify a w3id for which you are not listed as a maintainer. Right now I see listed:
> 
> * Raja Mazumder [mazumder@gwu.edu](mailto:mazumder@gwu.edu)
> * Vahan Simonyan [vahansim@gmail.com](mailto:vahansim@gmail.com)
> 
> Can you please contact them so the acknowledge this change is legit?
> Thanks!

Apologies @dgarijo. I have always been the one to make commits to this repository. When I set it up I did not list myself. If I did that now would that be enough?

**Comment by HadleyKing** [comment]
@dgarijo what are you specifically referring to here? Do you mean this repository or do you mean the site I am trying to add the redirect for?

**Comment by rajamazumder** [comment]
Yes, this change is good.

**Comment by dgarijo** [comment]
@HadleyKing I am referring to this repository. There is a readme, and you were not listed as a contributor, so I asked the original maintainers if the change was ok. To avoid this, please add yourself as a maintaner to the readme file.

**Comment by dgarijo** [comment]
@HadleyKing, I apologize, I see you are listed as a contributor in https://github.com/perma-id/w3id.org/blob/master/biocompute/readme.md
For some reason I didn't see the full list when I expanded the file in the PR.

**Pull request merged**
