### PR TITLE
Change URL from tovie.vn to chevie.vn

### PR DESCRIPTION
**Pull request by nguyenbahoang02**

### CODE REVIEW

**Comment by dgarijo** [comment]
@nguyenbahoang02 
you are not listed among the maintainers of this repository. Please ask
    * [Dat Trinh Tuan](mailto:dattt@soict.hust.edu.vn)
    * [Filip Kovacevic](mailto:filip.kovacevic@tuwien.ac.at)
    * [Fajar J. Ekaputra](mailto:fajar.ekaputra@wu.ac.at) ([@fekaputra](https://github.com/fekaputra))
For approval of this PR

**Comment by nguyenbahoang02** [comment]
How can I prove that I have received approval?

> @nguyenbahoang02 you are not listed among the maintainers of this repository. Please ask * [Dat Trinh Tuan](mailto:dattt@soict.hust.edu.vn) * [Filip Kovacevic](mailto:filip.kovacevic@tuwien.ac.at) * [Fajar J. Ekaputra](mailto:fajar.ekaputra@wu.ac.at) ([@fekaputra](https://github.com/fekaputra)) For approval of this PR

**Comment by dgarijo** [comment]
You may have any of those authors acknowledge your PR by answering here

**Comment by DatSOICT** [comment]
Dear @dgarijo ,

I am Dat Trinh Tuan (dattt@soict.hust.edu.vn), one of the maintainers of the repository. Could you please approve the pull request? Thank you very much for your assistance.

Best regards,
Dat Trinh Tuan

**Comment by dgarijo** [comment]
Please add the github ids of the maintainers in the readme so I can verify this more easily

**Pull request merged**
