### PR TITLE
Common Provenance Model identifier

### PR DESCRIPTION
**Pull request by RudoWittner**
I would like to create a new permatnent identifier for the Common Provenance Model RO Crate profile.

### CODE REVIEW

**Comment by dgarijo** [comment]
@RudoWittner please add a valid .htaccess with a redirection, as we don't reserve namespaces.
Thanks!

**Comment by TallTed** [comment]
Also, better to create `README.md` (which GitHub treats specially) than `readme.md`

**Comment by davidlehn** [comment]
Lower case `readme.md` works fine too.

**Comment by TallTed** [comment]
Huh! Something went sideways in another repo, and I thought that was the cause ... but I guess not!

**Pull request closed without merging**
