### PR TITLE
Create .htaccess

### PR DESCRIPTION
**Pull request by gero84**

### CODE REVIEW

**Comment by dgarijo** [comment]
@gero84,
can you please add a readme file with a description of the w3id and the maintainers?

**Comment by gero84** [comment]
Ok, where do I upload it?

**Comment by davidlehn** [comment]
@gero84 As another commit in this PR.

**Comment by gero84** [comment]
There should be a folder somewhere, right?

**Comment by gero84** [comment]
Please see here: https://github.com/perma-id/w3id.org/pull/1698

**Comment by dgarijo** [comment]
This can be done by updating the same PR, but I will merge it for now

**Comment by gero84** [comment]
Thanks, in case I want to make a change on the README.md I do it directly on your repository?

**Pull request merged**
