### PR TITLE
Add Namespace ProcessOntology to Steel

### PR DESCRIPTION
**Pull request by Kibubu**
The steel namespace will be split up into different working groups. The processing of steels is the topic of the current working group.

### CODE REVIEW

**Comment by dgarijo** [comment]
@Kibubu,
the target links are 404 (e.g., https://materialdigital.github.io/stahldigital-ontology-public/ProcessOntology/). Are you aware of this?

**Comment by Kibubu** [comment]
They will be up in around 30m Pipeline takes quite a while

**Comment by Kibubu** [comment]
Should be up now

**Comment by dgarijo** [comment]
I still get 404 for https://materialdigital.github.io/stahldigital-ontology-public/ProcessOntology/index.json. Is the link ok?

**Comment by Kibubu** [comment]
Not all serialization are yet available. Same issue with parent dir.

**Comment by Kibubu** [comment]
Thank you

**Pull request merged**
