### PR TITLE
update htaccess

### PR DESCRIPTION
**Pull request by saidfathalla**
change redirect of documentation.

### CODE REVIEW

**Comment by saidfathalla** [comment]
@davidlehn when doing content negotiation, it returns 301 then from the 2nd request it returns 303. Do you know how to solve this? N.B. it is working with the url https://w3id.org/seo/ not https://w3id.org/seo#

**Comment by saidfathalla** [comment]
@davidlehn  I found the problem is seo is in the root directory of w3id, but other ontologies, such as coil ontology, have their htaccess file in a sub directory. do you have a solution to this problem? i cannot change the right now.

**Comment by davidlehn** [comment]
If I understand your issue, then yes, it's going to do redirects like that.  It's an artifact of this service using apache.  What problem does that cause?  If you know of an apache configuration that would help with this, we can discuss that.

**Comment by saidfathalla** [comment]
@davidlehn could you please merge this changes first? the problem is when doing the content negotiation with vapour, it fails the test because it returns and empty response with 301. I tried other ontologies which have URL https://w3id.org/XXX, e.g. BCI-ontology

**Comment by davidlehn** [comment]
Can't merge this yet.  It has changes to the 'un' dir (again).  Fix this PR so it only has the changes you want.  Check here:
https://github.com/perma-id/w3id.org/pull/1338/files
Due to the 45(!) commits, this will be squashed when merging unless you fix that yourself first.

**Pull request closed without merging**
