### PR TITLE
Request for a new w3id.org

### PR DESCRIPTION
**Pull request by morbiolo**
I'm creating two new ontologies for biodiversity data. Would you please create a persistent URL for these ontologies?

Best Regards,

Sergio Morbiolo

### CODE REVIEW

**Comment by davidlehn** [comment]
Can you squash these commits into one?  Thanks.

There's nothing at those sites, do you plan to use these redirections long term?  Is that IP/port going to be somewhat stable?

It also would help to have some ownership and project info as comments in the .htaccess or in a README.

**Comment by morbiolo** [comment]
Can you squash these commits into one? Thanks. - Okay, I will
There's nothing at those sites, do you plan to use these redirections long term? Is that IP/port going to be somewhat stable? - The site is under development, we wil use it for a long time (ad eternum, if possible). It will going to be more or less stable, at least for some years from now.
It also would help to have some ownership and project info as comments in the .htaccess or in a README. - I'll do it

Thanks for your time, Sérgio Rodrigues Morbiolo
 

    Em Segunda-feira, 16 de Maio de 2016 17:50, David I. Lehn <notifications@github.com> escreveu:
 

 Can you squash these commits into one? Thanks.There's nothing at those sites, do you plan to use these redirections long term? Is that IP/port going to be somewhat stable?It also would help to have some ownership and project info as comments in the .htaccess or in a README.—

**Comment by dgarijo** [comment]
@morbiolo Any updates regarding the requested updates? Shall I close this pull request so you can do a new one?

**Comment by davidlehn** [comment]
No response. Closing. Reopen if needed.

**Pull request closed without merging**
