### PR TITLE
Fixed bug in rewrite rule

### PR DESCRIPTION
**Pull request by luca-martinelli-09**
Sorry for the many pull requests :(

### CODE REVIEW

**Comment by dgarijo** [comment]
@luca-martinelli-09,
no problem. I recommend having local tests next time

**Comment by davidlehn** [comment]
Not sure what's going on with all the commits listed here for a one line change.  The main history looks like it has squash commits too.  Maybe need to rebase this before future PRs.

**Comment by luca-martinelli-09** [comment]
> Not sure what's going on with all the commits listed here for a one line change. The main history looks like it has squash commits too. Maybe need to rebase this before future PRs.

Thank you for the advice, did it

**Comment by luca-martinelli-09** [comment]
> @luca-martinelli-09, no problem. I recommend having local tests next time

Thank you, I will

**Pull request merged**
