### PR TITLE
[ad4gd] Add mappings for custom ad4gd properties

### PR DESCRIPTION
**Pull request by avillar**
Add mappings for `https://w3id.org/ad4gd/properties/...` to hosted RAINBOW instance.

Please, @rapw3k confirm that the changes are ok.

Thank you.

### CODE REVIEW

**Comment by dgarijo** [comment]
@rapw3k any news?

**Review by rapw3k — APPROVED** [review]

**Comment by rapw3k** [comment]
yes all accepted thanks!

**Comment by rapw3k** [comment]
I added also @avillar as contributor, as we are both contributing to this project

**Comment by dgarijo** [comment]
@rapw3k fyi, you have not edited any files.

**Pull request merged**
