### PR TITLE
added SSL certificates in .htaccess

### PR DESCRIPTION
**Pull request by ilin-t**

### CODE REVIEW

**Comment by dgarijo** [comment]
hello @ilin-t,
I do not understand very well what you are trying to achieve with this change. w3id is https, but your URL is http. What do you gain by forcing everyone to be http? Isn't that the behavior by default?

**Comment by ilin-t** [comment]
Hello Daniel,

I have the issue that is addressed in Issue #1063. With this change i tried
to tackle the issue, and add the required certificates so i can open the
resources via URL in Protege.

**Comment by dgarijo** [comment]
I will merge the request to see if it works, but I don't think it will, as you still go from https to http. I have been wanting to research that issue for a while but got no time. Please let me know if this resolves it.

**Comment by ilin-t** [comment]
Unfortunately, it didn't.

**Comment by dgarijo** [comment]
Actually, this change broke it even more, because all URLs come from https and does not redirect. I am going to revert it

**Comment by ilin-t** [comment]
Yeah, i saw, i made a new request with the old rules.

**Comment by dgarijo** [comment]
Ok, now it doesn't load in protege, but redirects fine. This issue is very annoying. I addressed it in the past by doing my own content negotiation (if You do a CURL command, you can download the ontology and open it in Protege)  curl -sH  "accept:application/rdf+xml"  https://w3id.org/ontopbm-aquatic -L

**Comment by ilin-t** [comment]
Yes, that is one way.  You can also open the ontology by entering the url
after the redirect in protege.

**Pull request merged**
