### PR TITLE
adding cevo ontology

### PR DESCRIPTION
**Pull request by shekarpour**
Dear all

I added the folder of cevo which redirects the URIs of the cevo vocabulary, 
The repository of the vocabulary is here: https://github.com/shekarpour/cevo.io

I appreciate in case you accept that.

Thank you 

Saeedeh

### CODE REVIEW

**Comment by davidlehn** [comment]
This is just going to redirect https://w3id.org/cevo/, did you intend for https://w3id.org/cevo/ontology/ to work as well?

**Comment by shekarpour** [comment]
yes, please, I am using the four following prefix:
https://w3id.org/cevo/
https://w3id.org/cevo/ontology/
https://w3id.org/cevo/verb/
https://w3id.org/cevo/event/

the two later ones are used for the extended version.

Thank you

**Comment by shekarpour** [comment]
@dgarijo 
I updated the htaccess, for now we are going ahead only with https://w3id.org/cevo/ 
soon we will apply the further changes, I am sending a new pull request. 

Thanks @dgarijo

**Comment by shekarpour** [comment]
new pull request, could you please apply now for https://w3id.org/cevo/

**Pull request merged**
