### PR TITLE
Create new permanent id for RASH and its Framework

### PR DESCRIPTION
**Pull request by essepuntato**
This permanent ID space has been created for providing a way to permanently identify all the resources associated to the RASH Framework, i.e. a set of specifications and writing/conversion/extraction tools for writing academic articles in RASH, i.e., a markup language defined as a subset of HTML for writing scientific articles.

The responsible for this space is Silvio Peroni, who can be contacted by email (essepuntato@gmail.com) or twitter (@essepuntato).

### CODE REVIEW

**Comment by dgarijo** [comment]
@essepuntato,
could you please add a readme file as well? It would be sufficient to add your comment in there.
Thanks in advance!

**Comment by essepuntato** [comment]
Hi @dgarijo 

I always forget about it... Do I have to add the readme as an additional pull request, or I have to recreate the whole thing, so as to have one pull request with both the htaccess and the readme?

**Comment by dgarijo** [comment]
@essepuntato 
however you prefer :) . Can't you just update the pull request with the readme?

**Comment by essepuntato** [comment]
I Daniel,

I think I’ve created a new PR with the readme in the end, while trying to update the previous one.

Let me know if it works.

S.

**Pull request merged**
