### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Ahmedreyadh1985sh**

### CODE REVIEW

**Comment by Ahmedreyadh1985sh** [comment]
https://ahmedreyadh1985sh.github.io/GVT/gvt.html

**Comment by Ahmedreyadh1985sh** [comment]
تم الإرسال من Galaxy الخاص بي
-------- الرسالة الأصلية --------من: "David I. Lehn" ***@***.***> التاريخ: ٣‏/٣‏/٢٠٢٣  ٣:١٣ ص  (GMT+03:00) إلى: "perma-id/w3id.org" ***@***.***> نسخة: Ahmedreyadh1985sh ***@***.***>, Author ***@***.***> الموضوع: Re: [perma-id/w3id.org] Add files via upload (PR #3146) 
Closed #3146.

**Comment by Ahmedreyadh1985sh** [comment]
Thanks for replay I have an ontology and I want a permanent url and I am don't understand how I can receive itOr what should I do.Best wishes تم الإرسال من Galaxy الخاص بي
-------- الرسالة الأصلية --------من: "David I. Lehn" ***@***.***> التاريخ: ٣‏/٣‏/٢٠٢٣  ٣:١٣ ص  (GMT+03:00) إلى: "perma-id/w3id.org" ***@***.***> نسخة: Ahmedreyadh1985sh ***@***.***>, Author ***@***.***> الموضوع: Re: [perma-id/w3id.org] Add files via upload (PR #3146) 
Closed #3146.

**Comment by davidlehn** [comment]
The files in this PR look like the contents of a project.  I closed it because w3id is a redirect service, not a hosting service.  You should first find somewhere else to host your files.  (Many people here use GitHub Pages or raw file URLs, but any hosting service you like is fine.)  Then make a w3id PR with a directory that contains an Apache `.htaccess` file with the redirect rules you want, and a README.md with a brief details for this project and the github ids of people that maintain the redirect rules.  Take a look around at the other directories here are doing and make something similar as needed for your project.

**Pull request closed without merging**
