### PR TITLE
update 

### PR DESCRIPTION
**Pull request by jhaag75**
moving granular .htacces rules to root .htaccess for "adl" directory, removed old adl path on w3id.org

### CODE REVIEW

**Comment by jhaag75** [comment]
Is there an issue with this? Do I need to close and resubmit?

**Comment by halindrome** [comment]
I am sure you appreciate that tending this site is done with volunteer labor on an as-available basis.  We deal with pull requests as quickly as we can.  I am reviewing yours now.

**Comment by jhaag75** [comment]
Oh yes, my apologies. Was not trying to be forceful or anything. Was just curious about the Travis flag.

**Comment by davidlehn** [comment]
I started to look at that but got distracted.  Failure is because /xapi/adl is 404 for everything but application/ld+json.  Apparently the linkchecker doesn't like that.  I didn't look into how to fix it.

**Comment by perma-id** [comment]
I didn't either.  The Travis failures that we are seeing are so often
spurious I just assume its our fault.

On Wed, Feb 10, 2016 at 2:06 PM, David I. Lehn <notifications@github.com>
wrote:

> I started to look at that but got distracted. Failure is because /xapi/adl
> is 404 for everything but application/ld+json. Apparently the linkchecker
> doesn't like that. I didn't look into how to fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perma-id/w3id.org/pull/259#issuecomment-182556364>.
>



-- 
Shane McCarron
Managing Director, Applied Testing and Technology, Inc.

**Pull request merged**
