### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by Iniely**
I added my github id as a maintainer.

### CODE REVIEW

**Comment by dgarijo** [comment]
Sorry, this branch has conflicts with the main branch.
Also please sqash the commits

**Comment by davidlehn** [comment]
This is my fault, sorry.  An option was flipped yesterday and I rebased and merged your PR instead of just merging it.  You'll need to fix up your branch with something like:
```
# update and rebase on master
git fetch --all
git rebase orgin/master
# check log/history to make sure it just has the latest commit(s)
# force push your branch:
git push -f
```

**Comment by Iniely** [comment]
I followed the steps, and now it is fixed. Thank you :)

**Comment by davidlehn** [comment]
@Iniely Looks like that didn't work.  The [PR commits view](https://github.com/perma-id/w3id.org/pull/2122/commits) should just show the one new commit.

**Comment by Iniely** [comment]
Oh no. I'm going to do it again!.

**Review by davidlehn — APPROVED** [review]

**Pull request merged**
