### PR TITLE
Update .htaccess

### PR DESCRIPTION
**Pull request by Naeima**

### CODE REVIEW

**Comment by dgarijo** [comment]
@Naeima,
you are not listed as a maintainer of this w3id. Please have:
- Lukas König [lukas.koenig@fhstp.ac.at](mailto:lukas.koenig@fhstp.ac.at) or
- Sebastian Neumaier [sebastian.neumaier@fhstp.ac.at](mailto:sebastian.neumaier@fhstp.ac.at)
to accept this pull request.

**Comment by Naeima** [comment]
Hi,
I am new to this and would like to publish my ontology at w3id.org. Is this the correct way to do it?
Thanks,
Naeima

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dgarijo** [comment]
You have to create a new folder with the name of the w3id you want to reserve.
In this case you are changing someone else's, which is not allowed.
See https://github.com/perma-id/w3id.org/tree/master#creating-a-new-identifier for the instructions and https://github.com/perma-id/w3id.org/tree/master/example for an example

**Comment by Naeima** [comment]
Thank you for the heads up, I will delete the pull request now.
Best regards,
Naeima

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Naeima** [comment]
Hi Daniel,

I created and updated my request on the (.htacess) as follows:
Options +FollowSymLinks

# Rewrite engine setup
RewriteEngine On

# Redirect to w3id.org/foo/
RewriteRule^$ https://naeima.github.io/foo_html/ [R=303,L]
RewriteRule ^foo$ http://www.ontology/ns/foo# [R=302,L]
RewriteRule ^foo_1.1$ http://www.ontology/ns/foo/1.1# [R=302,L]

Please let me know how long it will take to redirect the IRIs.

Many thanks,
Naeima

________________________________

**Comment by dgarijo** [comment]
@Naeima,
the redirection is immediate (a few seconds).
Where did you update your PR? I cannot see it.

**Comment by Naeima** [comment]
Hi Daniel,

Are you still at the conference? Could we please meet f2f at you convivence?
I guess this one is ok https://naeima.github.io/foo_html/, right?

I just need help putting those URL(s) right 🙂

Thank you for your help,
Naeima
________________________________

**Comment by Naeima** [comment]
Many thanks, I will do that!
Best regards,
Naeima

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
