### PR TITLE
Create .htaccess

### PR DESCRIPTION
**Pull request by mohdnajib1985**
Publishing new ontology for fish

### CODE REVIEW

**Comment by dgarijo** [comment]
@mohdnajib1985 
Please add a readme file with the contact details of this w3id.
In addition, you seem to be redirecting the w3id https://w3id.org/dsablum/FishOntology/FishOntology. Is this correct?

**Comment by mohdnajib1985** [comment]
Hi Daniel Garijo,

Thank you for you message.
Actually I have been trying to edit a couple of URL. Since I saw that most
of my request failed, I thought something is wrong with my setup and have
play around a lot with it.

Ultimately I want to create a permanent address to my Fish Ontology,
preferably  https://w3id.org/dsablum/FishOntology/
<https://w3id.org/dsablum/FishOntology/FishOntology> where the
documentation can be accessed at
http://www.essepuntato.it/lode/owlapi/reasoner/https://raw.githubusercontent.com/mohdnajib1985/FishOntology/master/FishOntology.owl
 and the owl file can be accessed at
https://raw.githubusercontent.com/mohdnajib1985/FishOntology/master/FishOntology.owl


So far I have not been able to do it. Can you help me to configure this?
I have also put my contact details at the readme file.

Thanks.

**Comment by dgarijo** [comment]
@mohdnajib1985 
in the htaccess that I see in your PR you are only redirecting to a github file. You should replace those links with the links you want to redirect to.
In addition, I cannot see a readme file. Maybe you forgot to update the PR? Another detail is that the ontology you use is quite big to be using LODE constantly. I recommend you downloading the html page so it is served more quickly.

**Comment by davidlehn** [comment]
No response. Closing. Reopen if needed. Likely would need rebase, squash of commits, and a readme added.

**Pull request closed without merging**
