### PR TITLE
feat: add vaccine credentials vocab

### PR DESCRIPTION
**Pull request by tplooker**
Adds Vaccine Certificate Vocabulary for usage with Verifiable Credentials

### CODE REVIEW

**Review by OR13 — APPROVED** [review]

**Comment by davidlehn** [comment]
I'm not sure how we want to handle this.  Usually projects use their own top-level namespace.  That at least helps with managing who has edit control.  The `credentials` namespace is so old we haven't even documented who should be able to update it.  But in this case, I think it would be the CCG.  Is this request for an official CCG project and effectively under CCG control?  If so then it seems like here would be ok.  If not then it may be easier to manage in its own namespace.  The worry is everyone throwing projects in here and it being difficult to manange.

@dlongley @msporny Thoughts?  Who else should

**Comment by tplooker** [comment]
Ping @dlongley and @msporny, @OR13 and I were talking about whether we want to establish a pattern for name-spacing vocabs associated to VCs under the credential route, rather than having them in the root?

**Comment by OR13** [comment]
imo, it would be better to take this approach, because the alternative will be filling up w3id.org... and end of the day, its the remote host that matters... This probably should have been pointed at the latest vc-data-model ages ago...

**Comment by tplooker** [comment]
Appreciate the context @davidlehn, r.e the intent of the project, i do intend to propose it as a CCG work item just have not had the chance to prepare it yet.

**Comment by OR13** [comment]
I am in favor of merging this PR, and of making the CCG code owners for these redirects similar to how we have been evolving w3id.org/security ... which defines many of the same terms as w3id.org/security/jws for example.

**Comment by msporny** [comment]
> imo, it would be better to take this approach, because the alternative will be filling up w3id.org... and end of the day, its the remote host that matters... This probably should have been pointed at the latest vc-data-model ages ago...

This is not a concern, we shouldn't let the server drive the design. The goal here is short, memorable identifiers. I'm going to suggest the PR be changed to be under global top level directory -- /vaccination/ <-- we can accept that immediately.

**Comment by tplooker** [comment]
> This is not a concern, we shouldn't let the server drive the design. The goal here is short, memorable identifiers. I'm going to suggest the PR be changed to be under global top level directory -- /vaccination/ <-- we can accept that immediately.

Ok happy to change, I will amend now

**Comment by msporny** [comment]
> Ok happy to change, I will amend now

Thank you! :)

**Comment by tplooker** [comment]
ping @msporny @OR13 cannot request review in this repo, but should now be ready

**Review by msporny — APPROVED** [review]

**Review by OR13 — APPROVED** [review]

**Pull request merged**
