### PR TITLE
Update to dedicated domain

### PR DESCRIPTION
**Pull request by blake-regalia**

### CODE REVIEW

**Comment by dgarijo** [comment]
@blake-regalia, 
http://gnis-ld.org/lod/ gives a 404... wouldn't you prefer to fix it before doing the redirection?

**Comment by blake-regalia** [comment]
The above URLs resolves fine from my end, but it seems that for certain AS is routing to another machine on the same subnet. I will contact the servers' system administrator.

From my laptop, http://gnis-ld.org/lod/ redirects to the landing page as it should:
screen shot 2018-03-23 at 11 32 31 pm

**Comment by dgarijo** [comment]
To me, it redirects to http://sejp.geog.ucsb.edu/SWJPortal//lod
which returns a 404. 
http://sejp.geog.ucsb.edu/SWJPortal seems to work, but it's not the page you are looking for, I think.

Do you still want me to accept the redirect, or do you prefer to wait for your sys admin?

**Comment by blake-regalia** [comment]
Let's wait for the fix, thanks @dgarijo

**Comment by dgarijo** [comment]
Ok!,
just answer to this thread when the fix is done.

**Comment by blake-regalia** [comment]
Okay @dgarijo it should be all fixed now! Thanks

**Pull request merged**
