### PR TITLE
Bug fix redirect

### PR DESCRIPTION
**Pull request by essepuntato**
The redirect for the versions of the various ontologies were wrong.

### CODE REVIEW

**Comment by dgarijo** [comment]
This branch has conflicts with the main one and cannot be merged. Please refresh!

**Comment by essepuntato** [comment]
Hi Daniel,

It’s the first time I’ve seen this issue… How should I refresh this? Any hint is more that appreciated :-)

S.

**Comment by dgarijo** [comment]
Hi Silvio,
Try to update your repo from the master branch and do the commit again in another PR. I don't know very well the cause for the conflict. Maybe you were some commits behind because another collaborator had updated the link

**Comment by davidlehn** [comment]
Cause could be that we pulled in a previous request via the "squash" or "rebase" actions instead of a simple merge.  That works well when the PR branch is just thrown away afterwards.  But if work continues on that branch then it probably diverged and will have future merge issues like this.  I'm not sure what the best fix is for that.  Probably to checkout master, create a new branch from it, and cherry-pick the new commit to the new branch.  It will likely apply cleanly.  Or in cases like this just copy the change over.  Sorry for the trouble.

**Pull request merged**
