### PR TITLE
Update rewriting tools ...

### PR DESCRIPTION
**Pull request by gkirtzou**
... due to keeping versioned documentation of ontologies in the host server

### CODE REVIEW

**Comment by davidlehn** [comment]
Was this supposed to remove the `un/` files?

**Comment by dgarijo** [comment]
I am sorry, I reviewed the changes in the main htaccess but missed the changes to the un files. I don't think they should have been removed.

**Comment by davidlehn** [comment]
@gkirtzou I had to revert this.  Can you please redo the PR without the extra changes to the "un/" files.  Thanks.

**Comment by gkirtzou** [comment]
Sorry my mistake! I didn't notice that I messed up to UN folder. I will fix it and resubmit re pull request.

**Pull request merged**
