### PR TITLE
My feature=branch

### PR DESCRIPTION
**Pull request by biswanathdutta**
Requesting for redirect link

### CODE REVIEW

**Comment by dgarijo** [comment]
The latest PR still removes the root readme and htaccess, which should not change

**Comment by davidlehn** [comment]
I'm not sure what the problems are.  I've tried to help in email and here.  I'll try again.  This is what I'd suggest as a basic start-from-scratch method:
- Copy `codo/.htaccess` and `codo/README.md` into some other directory.
- Remove your local checkout of w3id.org.
- Remove your fork on github of w3id.org.
- Fork w3id.org again so it's a clean repo.
- Checkout your fork locally.
- Make a branch using something like `git checkout -b add-codo`.
- Make a `codo` dir.
- Put your `.htaccess` and `README.md` in that new dir.
- Commit only those two files with a message like "Add codo".
- Push to github.
- Go to your fork on github and make a PR.  Ensure only those two files are changed.
- We'll review and commit it.

That will solve the immediate issue.  If you have problems with the above it might be helpful to find someone local to assist. Next step is to learn more about git so this is easier in the future:
- Follow one or more of the fine git and github tutorials available online.

**Comment by biswanathdutta** [comment]
Thanks!!!

**Comment by davidlehn** [comment]
Added in https://github.com/perma-id/w3id.org/pull/1895, closing.

**Pull request closed without merging**
