### PR TITLE
update redirection to catch various content types

### PR DESCRIPTION
**Pull request by djodjoni**
relates to https://github.com/valueflows/valueflows/issues/207

ping @elf-pavlik

### CODE REVIEW

**Comment by dgarijo** [comment]
Please, don't use rawgit. It may cause problems when checking the availability and it's not a solution designed for in-production links. Instead you could use a gh-page.

**Comment by elf-pavlik** [comment]
Thanks @dgarijo we'll update this PR!

**Comment by djodjoni** [comment]
done

**Comment by davidlehn** [comment]
You should probably use https for github.io links.

**Comment by djodjoni** [comment]
@davidlehn yep probably yes for all. nice catch thx!

**Pull request merged**
