### PR TITLE
HTTP ontology

### PR DESCRIPTION
**Pull request by mthl**
Hello,

I would like to register the **http://w3id.org/http** namespace for an OWL ontology of HTTP interactions. Please let me know if you need more information.

Thanks

### CODE REVIEW

**Comment by OR13** [comment]
Interesting... any information about labs.nereide.fr / how this ontology will be maintained / used...

**Comment by mthl** [comment]
@OR13 This is early research work so maintenance and usage is pretty limited to that scope currently. `labs.nereide.fr` is the Gitlab CE instance of [Néréide](https://nereide.fr/) where this ontology is developed.

@dgarijo Thanks for merging.

**Comment by davidlehn** [comment]
I do have a concern about use of a common name like "http".  Looks like this currently being used only as a way to fetch the ontology file?  Was the plan to define ids in this namespace too or just use the w3c one?  In any case, I imagine it'll be ok since the current use looks appropriate.

**Comment by mthl** [comment]
Yes the plan is to define ids in this namespace instead of reusing the one from the W3C as it is currently done. I am in the process of migrating those ids.

**Pull request merged**
