### PR TITLE
Add rewerite rule for url https://figshare.com/articles/software/data_json/14607663

### PR DESCRIPTION
**Pull request by Maks-stack**

### CODE REVIEW

**Comment by dgarijo** [comment]
@Maks-stack,
have you left an extra space  on the folder name?

**Comment by Maks-stack** [comment]
Yes, sorry. I removed it

**Comment by Maks-stack** [comment]
This rewrite is for the seminar assignment. I tried to comply with the best practices, but I don't think it is necessary to merge this to the rewrite list. I just did it to get familiar with the process

**Comment by dgarijo** [comment]
@Maks-stack then do you want me to close the PR without merging?
You can use this w3id to redirect to your personal page.

**Comment by Maks-stack** [comment]
Yes this can be closed without merging. For future use I will create a new pull request

**Pull request closed without merging**
