### PR TITLE
add links for eddy4R.stor rmd and manuscript workflow.

### PR DESCRIPTION
**Pull request by kexu2014**
Please review. Thank you!

### CODE REVIEW

**Comment by dgarijo** [comment]
@kexu2014,
could you please add a readme file with a sentence describing the w3id and who the maintainer is?
Thanks in advance!

**Comment by kexu2014** [comment]
@dgarijo ,
Thanks for being so quick and responsive. I just added the README.md files. Please review and let me know how it goes. Thanks!

**Comment by dgarijo** [comment]
@kexu2014, 
I recommend removing the space in the "manuscript code" folder you have created.
If the w3id you want to create https://w3id.org/kxu/manuscriptCode? you should rename the folder "manuscriptCode"

**Comment by kexu2014** [comment]
@dgarijo ,
I just removed the space in the folder name. Please let me know what else I can do. Thanks again for your quick response!!

**Pull request merged**
