### PR TITLE
added masaka entry

### PR DESCRIPTION
**Pull request by mkanzaki**
please add my new permanent id. thank you

### CODE REVIEW

**Comment by mkanzaki** [comment]
Not sure about people/.htaccess write access. If it is a problem, pls ignore this and just add masaka directory.

**Comment by dgarijo** [comment]
This branch has conflicts with the main one and cannot be merged. I suggest closing this PR, updating to the latest version and then do another PR

**Comment by davidlehn** [comment]
Do you still want this?  Looks like you should just remove the line in `people/.htaccess` to resolve the conflict since the directory rules will do the same thing.

**Comment by davidlehn** [comment]
What's the status of this?

**Comment by davidlehn** [comment]
No response for about a year.  Closing.  Reopen if needed.

**Pull request closed without merging**
