### PR TITLE
Updates to w3ids for move to new system

### PR DESCRIPTION
**Pull request by chrisjh6**

### CODE REVIEW

**Comment by dgarijo** [comment]
@chrisjh6,
you are making a lot of changes to w3ids you didn't create originally. You are also not listed as a maintainer of the repository.
Can @IC-Standards  or @bobstuart confirm these changes? If they do, please also add yourself as a maintainer of the repository to avoid future confusion.
Thanks in advance

**Comment by chrisjh6** [comment]
I am a maintainer of this file. If you look at the history of the file you will see that I have been making changes to this file and associated pull-requests numerous times since its creation.

**Comment by dgarijo** [comment]
Ok! Could you please add yourself as a maintainer? It will make things easier to monitor in the future.

**Comment by chrisjh6** [comment]
Sure, I'll have Bob do it once he gets back to the office.

**Pull request merged**
