### PR TITLE
fix: bbs repository moved to different organization

### PR DESCRIPTION
**Pull request by ctomc**

### CODE REVIEW

**Comment by ctomc** [comment]
@OR13 @iherman Can one of you approve this change?

**Comment by iherman** [comment]
I am fine with these changes, but they probably are temporary until the document becomes an official W3C document in `https://www.w3.org/TR/`. One of you, or @OR13, should raise an issue in the `w3c/vc-di-bbs` repository to keep this problem open.

**Comment by dgarijo** [comment]
If the changes are fine but temporary, should they be merged?

**Comment by iherman** [comment]
> If the changes are fine but temporary, should they be merged?

https://w3c-ccg.github.io/vc-di-bbs/ yields a 404. That does not look good :-)

**Comment by ctomc** [comment]
I think this should be merged ASAP as currently things are broken.
Even if fix is temporary. We can always change it later on again.

**Comment by OR13** [comment]
Thank you for these fixes!

closing the related issue: https://github.com/w3c/vc-di-bbs/issues/74

**Pull request merged**
