### PR TITLE
Test

### PR DESCRIPTION
**Pull request by Amiaba**
Doing a test pull as a control

### CODE REVIEW

**Comment by davidlehn** [comment]
Was this supposed to be merged?  The name "Test" is a bit confusing.  Also the URLs listed don't have content.

**Comment by dgarijo** [comment]
I didn't check the target link, sorry. But apart from that the request is valid. I thought the "test" came from them testing w3id for the first time

**Comment by Amiaba** [comment]
Hi,

I’ve been trying to publish a test-ontology, my knowledge in this field is limited and I’ve been following a guide for how to publish ontologies, might have made a mistake?
Goal is to publish the ontology and then accessing it with a query, is there anything I have missed?

Regards

**Comment by dgarijo** [comment]
@Amiaba,
the link you are redirecting to, https://vocol.iais.fraunhofer.de/pizza2/ provides a 404. So the redirection won't serve your ontology

**Pull request merged**
