### PR TITLE
updates on .htaccess

### PR DESCRIPTION
**Pull request by tudorliv**

### CODE REVIEW

**Comment by dgarijo** [comment]
@tudorliv please add yourself as a maintainer in the readme file, so we know who is responsible for updates.
Also, please try to squash your commits, in order to avoid having a long history in the main repo

**Comment by tudorliv** [comment]
Maintainer: Tudor Liviana

**Comment by tudorliv** [comment]
Hi,

Thank you for your suggestions.

I updated the readme file with the name of the maintainer.

I made a Pull Request from a folder forked (https://w3id.org/iot-tta)
to be a permanent URI

for https://github.com/tudorliv/IoT-TTA/blob/main/IIoT_v1.3_fr.owl
I do not know if "Pull Request" is well done.

Can you help me with this?

Thank you,

Liviana Tudor


În sâm., 6 aug. 2022 la 13:15, Daniel Garijo ***@***.***> a
scris:

**Comment by dgarijo** [comment]
the PR looked ok, but you closed it.

**Pull request closed without merging**
