### PR TITLE
Fashion Trend Prediction / Colour aspect: entry for GitHub repo

### PR DESCRIPTION
**Pull request by srodriguez142857**
- Entry for the ongoing work regarding a "Fashion Trend Prediction" (FTP) project.
- Initial aspect: *Colour*

### CODE REVIEW

**Comment by dgarijo** [comment]
@srodriguez142857,
please add a readme file with a small description of the w3id you want to reserve and who the maintainers will be.
Thanks in advance!

**Comment by davidlehn** [comment]
The redirect target doesn't appear to exist.

**Comment by srodriguez142857** [comment]
@dgarijo 
Thank you for the feedback.  We are working on including more details about the ongoing project.
We will also include the current draft of the *FTP-Colour* ontology model and definition.

**Comment by srodriguez142857** [comment]
> The redirect target doesn't appear to exist.

@davidlehn 
The redirect target is this GitHub repo:  https://github.com/zishanqin/FTP---Colour-Ontology
image

I can access it from my end.  Also, I think the redirect rules in the `.htaccess` file are correct.
As mentioned, we will add the *README.md* file along with the current ontology draft of this project.

**Comment by dgarijo** [comment]
@srodriguez142857 your repository is private, that is why it looks like it yields a 404. If you want other people to access it, which I guess it's the reason to create a w3id, you should make it public

**Comment by srodriguez142857** [comment]
Dear @dgarijo and @davidlehn:
We have updated the GitHub repo entry.
We have created a specific organisation and public repo with our ongoing work.
We will release a companion Web site with more details about the FTP/Colour ontology soon.

**Pull request merged**
