### PR TITLE
Creation of 2 permanent URIs

### PR DESCRIPTION
**Pull request by fsteinemann**
Hi,

I would like to create permanent URIs with this pull request.

The first should be: www.w3id.org/OOSMP
The other: www.w3id.org/ecsel-dr-prc-sc-PMV

Hope I did everything correctly.

Can you also squash the 29 commits into 1 for me?

Thank you very much,
Fabian

### CODE REVIEW

**Comment by davidlehn** [comment]
- These files should be removed:
  - `test/.htaccess`
  - `test/README.MD`
  - `test1`
- Is this a mistake or should it be removed?
  - `ecsel-dr-prc-PMV.htaccess`
- Are the `ecsel-dr/*` files intended to be added?
- `ecsel-dr-prc-PMV/*` is going to a `ecsel-dr-sc-PMV` endpoint?
- I stopped reviewing there...

Please fix the PR, review and confirm the full PR patch, and make sure it's what you want.

**Comment by fsteinemann** [comment]
Hi David,

> These files should be removed:

I removed the files. I am sorry about that.


> Is this a mistake or should it be removed?

No, `ecsel-dr-prc-PMV.htaccess` is not a `mistake, I want to add the file

>  Are the `ecsel-dr/*` files intended to be added?

 Yes

> `ecsel-dr-prc-PMV/*` is going to a `ecsel-dr-sc-PMV` endpoint?

 I understand that seems strange but that is what I want.


Thanks for the feedback. I hope it is right this time.
Can you sqash all the commits into 1?
Thanks a lot

**Comment by davidlehn** [comment]
> > Is this a mistake or should it be removed?
> 
> No, `ecsel-dr-prc-PMV.htaccess` is not a `mistake, I want to add the file
> 

I wasn't clear.  I'm guessing you added this in the website UI and forgot a `/` in the middle.  Now there is one with the same name with the `/` but it has a different redirect.  Please remove the one without the `/` and make sure the other one has the right content.

**Comment by fsteinemann** [comment]
I now deleted the wrong .htaccess file.
I checked now: `ecsel-dr-prc-PMV.htaccess` in the folder `ecsel-dr-prc-PMW` is the file I want and it has the right content

**Comment by davidlehn** [comment]
@dgarijo We were supposed to squash this one into one commit.  No big deal.

**Comment by dgarijo** [comment]
Sorry about that!
Daniel

**Pull request merged**
