### PR TITLE
AT: Add missing base parameter

### PR DESCRIPTION
**Pull request by georgd**

### CODE REVIEW

**Comment by dgarijo** [comment]
@georgd,
 Carsten Klee  and Michael Luggen are listed as maintainers of this w3id. Please have any of them review and accept this pull request. Thanks in advance!

**Comment by georgd** [comment]
@cKlee @l00mi may I kindly ask you to review my pull request?

**Comment by l00mi** [comment]
It seems the old "more generic" query still works, will it be deprecated in the future?

**Comment by georgd** [comment]
Oddly, it sometimes works in the afternoon. Couldn't tell why, neither can the colleagues from OBVSG. However, they told me that this is the reliable way to get it.

There will be a bigger change towards the end of the year due to the finalisation of the technology changes which already made necessary the last update. But until then,, this fix should stay.

**Comment by dgarijo** [comment]
@l00mi please confirm the change so I can merge :)

**Comment by cKlee** [comment]
Hey, sorry. @dgarijo please merge the chenges. Thanks all!

**Pull request merged**
