### PR TITLE
Update Link and correct .htaccess

### PR DESCRIPTION
**Pull request by maxraupach**

### CODE REVIEW

**Comment by dgarijo** [comment]
Please add your github id in the maintainers list. It helps approving the PRs.

**Comment by maxraupach** [comment]
The github ID was added in the last commit, should i do another pull request for the update?

**Comment by dgarijo** [comment]
I do not see it in the readme. Which line are you referring to?

**Comment by maxraupach** [comment]
https://github.com/maxraupach/w3id.org/tree/master/GerPS-Ontology

in the Readme. i change the contacs to a table and added the id at the end.

btw ty for your help  =)

**Comment by dgarijo** [comment]
Sorry, not the github id (number), but I am looking at your github alias. Basically `maxraupach`.
We ask for this information so it's easier to verify your identity on your next PR.

**Comment by maxraupach** [comment]
oh ok! =) i will add this! =)

**Comment by maxraupach** [comment]
i updated the ID plus added a link to the persons account =)

**Comment by dgarijo** [comment]
You need to open a new pull request.

**Comment by maxraupach** [comment]
ok! i will do it! ty =)

**Pull request merged**
