### PR TITLE
Debug listdb/onto and provide detailed info about redirect expectatio…

### PR DESCRIPTION
**Pull request by SArndt-TIB**
Dear all,

thank you so much for accepting yesterday's [pull request](https://github.com/perma-id/w3id.org/pull/2836) so quickly :-) 

That enabled me to test my setup and debug it. I made some updates:
* corrections in the .htaccess files where buggy or missing 
* added more detailed info about what kind of responses I expect in different applications with a specific request
* current status of each sceanrio (resolves as expected/ unexpected resolve)
* added a directory for a scenario I would like to add to later

Thanks again!

Susanne

### CODE REVIEW

**Comment by dgarijo** [comment]
@SArndt-TIB,
you are trying to modify a w3id for which you are not listed as a maintainer. Please have Maximilian Bäumler approve the root PR

**Comment by SArndt-TIB** [comment]
Thanks @dgarijo , I will do that. Due to vacation time, this may take a couple of days.

Not being listed as a maintainer of w3id.org/listdb is an oversight on my part. I registered both w3ids listdb and listdb/onto and am practically maintainer for both. I should probably add my contacts to listdb as well?

**Comment by dgarijo** [comment]
yes, you should :)

**Comment by SArndt-TIB** [comment]
Okay, I updated that now. Thanks :-)

**Pull request merged**
