### PR TITLE
Version 0.3

### PR DESCRIPTION
**Pull request by tobiasgrubenmann**

### CODE REVIEW

**Comment by dgarijo** [comment]
@tobiasgrubenmann,
do you mind also adding a readme file with a description of the w3id (1 line) and adding yourself as a maintaner?
We are requesting this for maintainability purposes.
Thanks in advance

**Comment by davidlehn** [comment]
@tobiasgrubenmann Did you still need this update?  If so could you please also add maintainer github account info to the top level .htaccess or to a top level readme?  Thanks.

**Comment by davidlehn** [comment]
@tobiasgrubenmann ping

**Comment by dgarijo** [comment]
Closing this pull request due to inactivity. Please reopen if needed, @tobiasgrubenmann

**Pull request closed without merging**
