### PR TITLE
SARO Ontology permanent namespace

### PR DESCRIPTION
**Pull request by scerrisimon**
The namespace of the ontology (available at the rewrite rule URI) will be changed to:

w3id.org/saro#

### CODE REVIEW

**Comment by dgarijo** [comment]
@scerrisimon, you are not redirecting to the right file if you plan to serve ttl/html. I suggest you use a github page for this.

**Comment by dgarijo** [comment]
@scerrisimon,
same thing applies for the rdfs/turtle files.
Also, shouldn't the html redirect be 303?

**Comment by scerrisimon** [comment]
Fixed issue with 302-303, changed rdfs to rdf file extension. Set up html as a page and also ttl and rdf files are directly accessible. I hope this is now according to standard!

**Comment by scerrisimon** [comment]
Updated Readme file with contact info. Awaiting further instructions..

**Comment by dgarijo** [comment]
In line 13 you have "© 2019 GitHub, Inc.", which is not valid syntax.
Also, in line 7 why do you have RewriteRule ^/?$ https://elisasibarani.github.io/SARO/ [R=303,L]
instead of just RewriteRule ^$ https://elisasibarani.github.io/SARO/ [R=303,L]
?

**Comment by scerrisimon** [comment]
Thnks for your patience. I was using a 'template' (or so I thought) from another w3id example. Removed the issues and committed!

**Comment by davidlehn** [comment]
@scerrisimon Rules are processed in order.  The default one listed first will be used before the type detection ones are checked.  You should move that rule to the bottom.

**Pull request merged**
