### PR TITLE
Add /user

### PR DESCRIPTION
**Pull request by melvincarvalho**
User vocab is a modern vocab based on JSON-LD that tries to capture the useful parts of FOAF, vcard, activity streams, schema.org and other user related vocabs

The aim is to create a simple, practical and documented set of examples to allow users to publish linked data user profiles to the web

I've spoken to danbri, and he said there isnt an issue with trying this out

Contact: Melvin Carvalho
Email: melvincarvalho@gmail.com
WebID: https://melvincarvalho.com/#me
I also chair the w3c read write web community group: https://www.w3.org/community/rww/

### CODE REVIEW

**Comment by melvincarvalho** [comment]
Github README: https://github.com/melvincarvalho/user

**Comment by dgarijo** [comment]
@melvincarvalho,
please add the contact + info in a readme file with the htaccess.

**Comment by melvincarvalho** [comment]
Done: https://github.com/melvincarvalho/user#contacts

**Comment by dgarijo** [comment]
@melvincarvalho, please add a new readme file together with the htaccess with that information, not in your user repository

**Comment by melvincarvalho** [comment]
Added :)

https://github.com/melvincarvalho/w3id.org/tree/master/user

**Pull request merged**
