### PR TITLE
carsa-loci

### PR DESCRIPTION
**Pull request by nicholascar**
A simple PID for a Linked Data system - CaRSA LocI.

These PIDs will be used to ensure that references to the CaRSA LocI system in papers and in catalogues don't break as the system gets handed from the builder (my company) to the operator (government department).

### CODE REVIEW

**Comment by dgarijo** [comment]
@nicholascar I thought you had privileges now. Is it not the case still?

**Comment by nicholascar** [comment]
image

Seems not! No write privileges for me.

**Comment by dgarijo** [comment]
:( @davidlehn can you please add @nicholascar to write access to the repo. I cannot

**Comment by davidlehn** [comment]
@dgarijo I don't have org admin access either.  Continuing this onboarding discussion in https://github.com/perma-id/w3id.org/issues/1954.

**Pull request merged**
