### PR TITLE
separate out privateKeyJwk to separate context

### PR DESCRIPTION
**Pull request by kdenhartog**

### CODE REVIEW

**Comment by dgarijo** [comment]
@kdenhartog,
you are not listed among the maintainers of this w3id. 
Please contact any of the maintainers in https://github.com/perma-id/w3id.org/blob/master/security/README.md to approve this PR

**Comment by kdenhartog** [comment]
@OR13 @msporny @dlongley @davidlehn what's your take on this split? There's a subsequent PR referenced above to create the separate context as well in the lds-jws2020 suite that will align with this PR.

**Comment by OR13** [comment]
This PR should not be merged. 

There is a fundamental misunderstanding when it comes to the relationship between vocabularies and cyber security... and its not going to be resolved by creating more JSON-LD context files.

Please hold until the W3C VCDM 2.0 has guidance on this issue.

**Comment by kdenhartog** [comment]
I'm fine with closing this until it gets figured out over there, since this PR would probably be sitting open for 6+ months. Feel free to reopen if it's decided to be a good path to go.

For perspective, the main reason I'm arguing for this is to ontologically separate private and public data. I don't expect that it's going to offer any additional cybersecurity benefits, so wouldn't be arguing for it on those grounds.

**Pull request closed without merging**
