### PR TITLE
fix: fixes #2945

### LINKED ISSUE #2945: Fix broken redirect in rebase entry
Current redirect entry uses .org instead of .xyz.

### PR DESCRIPTION
**Pull request by awoie**
fixes #2945

### CODE REVIEW

**Comment by awoie** [comment]
@OR13 can you please confirm?

**Comment by OR13** [comment]
Looks good to me

**Comment by davidlehn** [comment]
README.md needs an update too.

**Comment by OR13** [comment]
@davidlehn which readme?

**Comment by TallTed** [comment]
@OR13 — `rebase/README.md` (in the https://github.com/spruceid/w3id.org/tree/awoie/fix-2945 branch) ... i.e., the one alongside the `.htaccess` being changed by this PR ... where two instances of `spec.rebase.org` need to be changed to `spec.rebase.xyz` to match the revised `.htaccess` content

**Comment by awoie** [comment]
Updated the README @davidlehn @OR13

**Review by OR13 — APPROVED** [review]

**Pull request merged**
