### PR TITLE
Update redirects to use correct domain, version

### PR DESCRIPTION
**Pull request by mr-c**
@tetron, please review -- thanks!

### CODE REVIEW

**Comment by dgarijo** [comment]
@mr-c,
please avoid using rawgit.com. See https://github.com/perma-id/w3id.org/issues/394
You can use github pages to avoid this issue.

**Comment by davidlehn** [comment]
We can merge this if you want.  Just be aware of the issues with using rawgit.

**Comment by mr-c** [comment]
Fixed, thanks

**Comment by davidlehn** [comment]
@mr-c Just to check, you did want this merged, right?  If not, I'll revert.

**Comment by mr-c** [comment]
@davidlehn Yes, thank you!

**Pull request merged**
