### PR TITLE
Update .htaccess

### PR DESCRIPTION
**Pull request by jhaag75**
Update to return JSON to browser for context doc

### CODE REVIEW

**Comment by dgarijo** [comment]
@jhaag75 
It seems like you have added the an existing id. Maybe it's a typo?

**Comment by jhaag75** [comment]
It's not a typo. Need this id to return JSON-LD if requested no matter what as it's planning to be used for a persistent JSON-LD @context id.

**Comment by dgarijo** [comment]
The first rule overwrites the second rule, right?
Then why have the second?

**Comment by jhaag75** [comment]
Does it? If so I will remove and resubmit.

**Comment by dgarijo** [comment]
Line 42 states to return profile-context.jsonld no matter what you ask for. Then line 44 states to return that very same file when you ask for json-ld

**Pull request closed without merging**
