### PR TITLE
init pull for our ontology 

### PR DESCRIPTION
**Pull request by llin-csiss**
we are still developing the ontology

### CODE REVIEW

**Comment by dgarijo** [comment]
@llin-csiss,
can you please add maintainer contact info in the readme file?
Thanks!

**Comment by llin-csiss** [comment]
hi, 
just added the contact info.
Thank you!

**Comment by dgarijo** [comment]
Hi again,
sorry but if you don't want to add an email can you please add your github id?
(add `@llin-csiss` in the readme file). I ask because if you do edits in this w3id I need to verify it's you and not someone else. Thanks in advance

**Comment by llin-csiss** [comment]
Hello,
Just added as you requested,
thanks!

**Comment by dgarijo** [comment]
Thanks.
Just fyi, you can enable your w3id to serve your ontology/documentation using the same URL. See an example here: https://github.com/perma-id/w3id.org/blob/master/example/.htaccess

**Comment by llin-csiss** [comment]
@dgarijo thanks a lot for your help!
I am just starting building the ontology. The example you provided are very helpful.

**Pull request merged**
