### PR TITLE
Change ip address of target server

### PR DESCRIPTION
**Pull request by matt-wallis**

### CODE REVIEW

**Comment by dgarijo** [comment]
@matt-wallis,
any possibility that you store files on a more permanent URL?  51.15.69.110 doesn't look very permanent. For example, since most are files, you could have them in a github page

**Comment by matt-wallis** [comment]
@dgarijo ,
I'm not sure I understand what you are asking. Are you asking me to change something?

**Comment by dgarijo** [comment]
@matt-wallis I am suggesting you to use URLs that are more permanent than an IP such as 51.15.69.110. Otherwise we will have to be changing the w3id every time the IP changes.

**Comment by matt-wallis** [comment]
I have no expectation that the ip address will change - I am paying for a fixed IP address. The change in this pull request was due to me moving to a new server. I forsee no reason to change it again.

**Pull request merged**
