### PR TITLE
[bot] Add a redirection rule for particular ontology versions.

### PR DESCRIPTION
**Pull request by attadanta**
Address [bot #80](https://github.com/w3c-lbd-cg/bot/issues/80).

This change adds a rule redirecting requests to a specific ontology version. It also fixes the jsonld and n-triples redirections.

A live environment has been setup for review at http://bot.mischung.net (live for the next 1-2 weeks). Here's a test suite that exercises the redirection rules (requires `curl`):

```bash
#!/bin/bash
set -euo pipefail

# Usage: ./test.sh source-url target-url

function get_url() {
  local url=$1
  local accept_header=$2

  curl -s -i -H "Accept: $accept_header" -o /dev/null -D - $url \
    | grep 'Location:' \
    | cut -d ' ' -f2 \
    | tr -d '\r'
}

function assert_location_equals() {
  local actual=$1
  local expected=$2

  if [ $actual == $expected ]; then
    echo ✅
  else
    echo ❌
  fi
}

function test_case() {
  local request_url=$1
  local expected_location=$2
  local accept_header=${3:-text/turtle}

  local location_response="$(get_url $request_url $accept_header)"
  local test_result="$(assert_location_equals $location_response $expected_location)"

  echo "$test_result $1 [$3] -> $2"
}

test_case "$1/" "$2/index.html" "text/html"
test_case "$1/bot" "$2/bot.rdf" "application/rdf+xml"
test_case "$1/bot" "$2/bot.ttl" "text/turtle"
test_case "$1/-0.1.2" "$2/bot-0.1.2.ttl" "text/turtle"
test_case "$1/0.3.2" "$2/bot-0.3.2.ttl" "text/turtle"
test_case "$1/0.3.2" "$2/bot-0.3.2.ttl" "application/n-triples"
test_case "$1/0.3.2" "$2/0.3.2" "text/html"
test_case "$1/RECAlignment" "$2/RECAlignment.html" "text/html"
test_case "$1/DOGONTAlignment" "$2/DOGONTAlignment.n3" "text/n3"
test_case "$1/BRICKAlignment" "$2/BRICKAlignment.nt" "application/n-triples"
test_case "$1/SCHEMAORGAlignment" "$2/SCHEMAORGAlignment.jsonld" "application/ld+json"
```

To run against the test environment:

```bash
./test.sh http://bot.mischung.net https://w3c-lbd-cg.github.io/bot
```

To test against the live environment at w3id.org:

```
./test.sh http://bot.mischung.net https://w3c-lbd-cg.github.io/bot
```

### CODE REVIEW

**Comment by dgarijo** [comment]
@attadanta,
you are trying to modify a w3id for which you are not listed as a maintainer. Please discuss it with them and have them confirm the approval to your edits here.  
The current listed maintainers are: 

    Mads Holten Rasmussen mhoras@byg.dtu.dk
    Pieter Pauwels pipauwel.pauwels@ugent.be
    Maxime Lefrançois maxime.lefrancois@emse.fr
    Georg Schneider georg.schneider@ibp.fraunhofer.de

**Comment by GeorgFerdinandSchneider** [comment]
Dear @dgarijo ,

thank you for being cautious with the maintainers of w3id.org/bot namespace.

I have been in close contact with @attadanta , which helped us to resolve the problem redirecting also version IRIs of BOT. I tested the .htaccess and script. The PR can be merged and is supported by the maintainers.

Best

Georg

P.S.: @attadanta the test above should be called via 

> ./test.sh https://w3id.org/bot https://w3c-lbd-cg.github.io/bot

for the w3id.org testcase?

**Review by GeorgFerdinandSchneider — APPROVED** [review]
Thanks @attadanta  for providing the changes and update. All fine

**Comment by dgarijo** [comment]
@attadanta,
can you please add your name to the maintainer list then? This will help in future updates.
Thanks @GeorgFerdinandSchneider !

**Comment by attadanta** [comment]
Thanks for the approval and prompt merge. I don't think I'd be able to contribute much more to the project, but if I do, I'll make sure to update the maintainers list.

@GeorgFerdinandSchneider , you are right, I had a mistake in the sample usage above. This has now been corrected. The test suite passes against w3id.org!

**Pull request merged**
