### PR TITLE
Added mapping for linked data

### PR DESCRIPTION
**Pull request by atorjusen**

### CODE REVIEW

**Comment by dgarijo** [comment]
This redirection will make URLs such as http://w3id.org/readi/z018-asset/someasset not work

**Comment by atorjusen** [comment]
Hi Daniel, 
I have probably misunderstood something here. 

To take another example: I thought this rewrite rule

RewriteRule ^(.*) https://demo-irm-dnvgl.northeurope.cloudapp.azure.com/readi/$1 [R=303,NE,L]
 
Would cause: 
http://w3id.org/readi/z018-rdl/NOZTI_10
To redirect to: 
https://demo-irm-dnvgl.northeurope.cloudapp.azure.com/readi/z018-rdl/NOZTI_10

and 
http://w3id.org/readi/z018-asset/someasset
to redirect to 
https://demo-irm-dnvgl.northeurope.cloudapp.azure.com/readi/z018-asset/someasset

This is what happend when I tested using a local server and it is what I want. 
(Note that so far there is no content at the last URI: 
https://demo-irm-dnvgl.northeurope.cloudapp.azure.com/readi/z018-asset/someasset) 

If I am mistaken in this, is the solution to specify explicit mappings like the ones below, or is there another problem here? 

RewriteRule ^rdl/(.*) https://demo-irm-dnvgl.northeurope.cloudapp.azure.com/readi/rdl/$1 [R=303,NE,L]
RewriteRule ^z018-requirements/(.*) https://demo-irm-dnvgl.northeurope.cloudapp.azure.com/readi/z018-requirements/$1 [R=303,NE,L]
RewriteRule ^z018-rdl/(.*) https://demo-irm-dnvgl.northeurope.cloudapp.azure.com/readi/z018-rdl/$1 [R=303,NE,L]
RewriteRule ^z018-asset/(.*) https://demo-irm-dnvgl.northeurope.cloudapp.azure.com/readi/z018-asset/$1 [R=303,NE,L]

**Comment by dgarijo** [comment]
@atorjusen what I meant is that originally you had a rewrite rule for z018 asset. Therefore, the w3ids http://w3id.org/readi/ will be handled by w3id, but anything after will be handled by your own server. I will merge the PR, because it looks like it's the behavior you want

**Comment by atorjusen** [comment]
Thanks

**Pull request merged**
