### PR TITLE
Adding EVENTSKG dataset

### PR DESCRIPTION
**Pull request by saidfathalla**
I just added two files for the new dataset in this request. I created a new brach but when i press "compare and pull request" it shows "There isn’t anything to compare.
perma-id:master and saidfathalla:eventskg-Dataset are entirely different commit histories." I dont know what is the problem, and why all 50 commits appear in each PR.

### CODE REVIEW

**Comment by davidlehn** [comment]
You need to update your master branch to resync it with the upstream master.  We squashed your previous PRs to remove the churn of intermediate development commits.  All those commits are probably still in your repo, so a PR will see them as changes against upstream.  GitHub page for your master branch says this: "This branch is 50 commits ahead, 26 commits behind perma-id:master."  I don't know how this gets fixed with the GitHub UI.  Easier with the command line tool.

**Comment by saidfathalla** [comment]
could you please tell me hoe to do it with command line tool? this is the new branch https://github.com/saidfathalla/w3id.org/tree/eventskg-config

**Comment by davidlehn** [comment]
I'd add a remote to the main upstream repo, reset your master to sync with upstream, create a new branch, cherry-pick your new changes into it, and make a PR out of that.

**Comment by saidfathalla** [comment]
done. This is the new branch https://github.com/saidfathalla/w3id.org/tree/eventskg-Dataset.

**Comment by davidlehn** [comment]
I don't know what you are attempting to do there or what you want us to do with it.  Make a branch off of master HEAD, add your commits to that, and make a PR.  Also you can't add or change the root README.md.

**Comment by saidfathalla** [comment]
when creating PR from the new branch it give "There isn’t anything to compare." Why do you don't want to merge the PR from master?
What i  want is ti create a new PURL for EVENTSKG (https://github.com/saidfathalla/w3id.org/tree/eventskg-Dataset). thats all.

**Comment by davidlehn** [comment]
Closing due to merging of https://github.com/perma-id/w3id.org/pull/1363.

**Pull request closed without merging**
