### PR TITLE
also add an example for the CH- branch of ISIL

### PR DESCRIPTION
**Pull request by l00mi**

### CODE REVIEW

**Comment by dgarijo** [comment]
@l00mi,
sorry but you are changing the w3id reserved and maintained by Carsten Klee. Can you contact him to acknowledge this change?

**Comment by l00mi** [comment]
Thank you for pinging, I already send him an eMail. Pinging @cKlee  here for reference too.

**Comment by dgarijo** [comment]
No problem. It would be nice if you also add yourself in the meantime to the maintainers so we don't have this issue next time :)

**Comment by l00mi** [comment]
Absolutely, this is per root path, or is there a global list?

**Comment by cKlee** [comment]
Hey. Thank you very much for the contribution. Looks great. Please merge!

**Pull request merged**
