### PR TITLE
Update .htaccess

### PR DESCRIPTION
**Pull request by jhaag75**
udpate to rules for seriousgames vocab

### CODE REVIEW

**Comment by dgarijo** [comment]
Arent't thre redundant redirections here?
 +# Serve Constrained JSON-LD at vocabulary IRI if JSON is requested
+RewriteCond %{HTTP_ACCEPT} application/json
+RewriteRule ^seriousgames/?$ http://www.e-ucm.es/xapi/seriousgames.jsonld [R=303]
+
+# Serve Constrained JSON-LD at vocabulary IRI if JSON is requested
+RewriteCond %{HTTP_ACCEPT} application/json
+RewriteRule ^seriousgames/(.*)$ http://www.e-ucm.es/xapi/seriousgames.jsonld [R=303]
Those two basically do the same thing, right?

**Comment by jhaag75** [comment]
I don't think they are redundant, but I'm open to making any improvements
you might offer.


This rule rule returns the JSON document if
https://w3id.org/xapi/seriousgames/ with our without slash is requested:

RewriteCond %{HTTP_ACCEPT} application/json
RewriteRule ^seriousgames/?$ http://www.e-ucm.es/xapi/seriousgames.jsonld
 [R=303]

This rule rule returns the JSON document if
https://w3id.org/xapi/seriousgames/anyterm is requested:

# Serve Constrained JSON-LD at vocabulary IRI if JSON is requested
RewriteCond %{HTTP_ACCEPT} application/json
RewriteRule ^seriousgames/(.*)$ http://www.e-ucm.es/xapi/seriousgames.jsonld
 [R=303]

-------------------------------------------------------
+1.850.266.7100(office)
+1.850.471.1300 (mobile)
jhaag75 (skype)
http://jasonhaag.com (Web)
http://twitter.com/mobilejson (Twitter)
http://linkedin.com/in/jasonhaag (LinkedIn)

**Comment by dgarijo** [comment]
Sorry, they are not redundtant. But if you look at the best practices: https://www.w3.org/TR/swbp-vocab-pub/#recipe4, you may need to replace the ".*" with ".+". Otherwise I'm afraid the redirection might trigger both rules.

**Comment by jhaag75** [comment]
The (.*) is intentional.

See, https://httpd.apache.org/docs/trunk/rewrite/intro.html

The regex is to repeat the previous match 0 or more times.

I've had these rules working previously just fine for awhile now. The main
change here is that I added a  new ruleset for /seriousgames/. It is using
the exact same rules, just pointing to a different server for resolution
now.



-------------------------------------------------------
+1.850.266.7100(office)
+1.850.471.1300 (mobile)
jhaag75 (skype)
http://jasonhaag.com (Web)
http://twitter.com/mobilejson (Twitter)
http://linkedin.com/in/jasonhaag (LinkedIn)

**Comment by dgarijo** [comment]
@jhaag75,  
I understand what the (.*) does. I just wanted to point out that if you have a rule for 0 characters after the slash and another for 0 or more, you may have enough with the second one, since it includes the case modeled by the first one. In any case, since both redirect to the same page I will merge the commit. It was just a suggestion.

**Comment by jhaag75** [comment]
Thank you Daniel

**Comment by dgarijo** [comment]
No worries!

**Pull request merged**
