### PR TITLE
Add /security/suites/secp256k1recovery-2020

### PR DESCRIPTION
**Pull request by clehner**
As discussed here: https://github.com/w3c-ccg/security-vocab/pull/95

### CODE REVIEW

**Comment by dgarijo** [comment]
@clehner,
 sorry, you are not listed as a maintainer of this w3id. Please have: @dlongley, @davidlehn, @msporny or @OR13 approve this request

**Comment by OR13** [comment]
Looks good to me!

**Comment by davidlehn** [comment]
I have a concern about the direction of this `/security` endpoint.  It's turning into a bit more of a kitchen sink than most endpoints.  And tracking who can update which sub-rules is going to be a bit more challenging than usual.

This context is defining things off in it's own namespace.  The other contexts here are (I think) all using `https://w3id.org/security#` as a base.  This new one is using `https://identity.foundation/EcdsaSecp256k1RecoverySignature2020#`and redefining properties such as `publicKeyJwk`, `privateKeyJwk`, and others with this new base vs how it's defined in the other jws context.  Seems like this may get confusing or just outright start conflicting if you use both contexts at once.

**Comment by msporny** [comment]
> I have a concern about the direction of this `/security` endpoint. It's turning into a bit more of a kitchen sink than most endpoints. And tracking who can update which sub-rules is going to be a bit more challenging than usual.

To address this concern, we should split this single .htaccess file into multiple directories containing .htaccess files.

> This context is defining things off in it's own namespace.

Yes, the `EcdsaSecp256k1RecoverySignature2020` JSON-LD Context is broken... it'll only blow up on people using `EcdsaSecp256k1RecoverySignature2020`... which is a good thing, and exactly the sort of behavior we want (so this sort of thing doesn't take the rest of the ecosystem down with them).

@clehner, you may want to follow this example instead:

https://raw.githubusercontent.com/digitalbazaar/ed25519-signature-2020-context/master/contexts/ed25519-signature-2020-v1.jsonld

You may also want to avoid providing terms to express private key values in public contexts... private key values shouldn't escape your systems.

**Comment by msporny** [comment]
The registration is fine, however... we should let this through and refactor later. 

@clehner -- please note the ticking time bomb that is your JSON-LD Context. This repo doesn't care about that, but you should (as an implementer). :)

**Comment by clehner** [comment]
Thanks @msporny. Noted:
https://github.com/decentralized-identity/EcdsaSecp256k1RecoverySignature2020/issues/14
https://github.com/decentralized-identity/EcdsaSecp256k1RecoverySignature2020/issues/15

**Pull request merged**
