### PR TITLE
feat: add HIMIKO

### PR DESCRIPTION
**Pull request by junjun7613**
Create HIMIKO repository

### CODE REVIEW

**Comment by junjun7613** [comment]
Create HIMIKO repository

**Comment by junjun7613** [comment]
updates htaccess

**Comment by junjun7613** [comment]
Updated README.md

**Comment by dgarijo** [comment]
@junjun7613 can you please add your github user to the maintainer list? It's easier to identify ownership in for future edits of this w3id.

**Comment by junjun7613** [comment]
@dgarijo I did add my user info to README. Is it what you want me to do? Thanks!

**Comment by dgarijo** [comment]
Yes. Thanks

**Pull request merged**
