### PR TITLE
Added entry for DeepPhe Project documentation

### PR DESCRIPTION
**Pull request by JohnLevander**

### CODE REVIEW

**Comment by dgarijo** [comment]
@JohnLevander,
please add a readme stating who the maintainer of this w3id will be. See https://github.com/perma-id/w3id.org#new for details

**Comment by dgarijo** [comment]
@JohnLevander thanks. Can you please add yourself as a maintainer too, so if you add changes to this PR I know it's you?  jdl is not very intuitive. Thanks in advance!

**Comment by JohnLevander** [comment]
Okay done, sorry about that.

**Comment by dgarijo** [comment]
No problem. In the future you can add your github id as a maintainer, as that's enough

**Pull request merged**
