### PR TITLE
Create .htaccess

### PR DESCRIPTION
**Pull request by LeonardoForero**

### CODE REVIEW

**Comment by dgarijo** [comment]
Sorry, we don't allow reserving w3ids. Can you please add the link to the redirection?

**Comment by LeonardoForero** [comment]
Excuse me, I'm a beginner!

RewriteRule ^test-a# https://github.com/LeonardoForero/Knowls-Ontologies/blob/master/test-a.owl [R=303,NE,L]

**Comment by davidlehn** [comment]
- You should add that to the .htaccess file.  Look at other files for examples.
- That github resources doesn't exist.
- If it did exist, that redirect would go to the github UI for that file vs serving it directly.  Consider the raw resource URLs, github pages hosting, or other hosting.

**Comment by LeonardoForero** [comment]
I've updated the ".htaccess" file. Please find the ajustements!

**Comment by davidlehn** [comment]
Can you also please add a short README.md with basic info like a title, maybe a reference url, and a contact?

If you just need simple redirects you could simplify the .htaccess file by removing the AddType and RewriteCond parts.  That's more useful when redirecting to different resources based on request accept headers.

**Comment by dgarijo** [comment]
@LeonardoForero,
I don't recommend adding your phone number, your github id or your email is enough.

**Comment by dgarijo** [comment]
Also, you are doing a 303 redirection, typically used for semantic-web resources. But you only serve one resource. If so, why not a 302?

**Pull request merged**
