### PR TITLE
Permanent URIs for the Italian OntoPiA ontology network for publ…

### PR DESCRIPTION
**Pull request by giorgialodi**
…ic administrations

### CODE REVIEW

**Comment by dgarijo** [comment]
@giorgialodi,
why 302 instead of 303, which is meant for semantic web reosurces?

**Comment by giorgialodi** [comment]
We chose 302 because it is temporary

**Comment by dgarijo** [comment]
Even if temporary, according to W3C recommendations https://www.w3.org/TR/swbp-vocab-pub/ it is better to use 303 when doing semantic resource redirection. I am afraid that validators such as vapour won't validate the URI of your ontology otherwise.

**Comment by giorgialodi** [comment]
we updated the .htaccess files with 303, even if we noticed other merged projects about ontologies with 302 code too.

**Pull request merged**
