### PR TITLE
Update .htaccess

### PR DESCRIPTION
**Pull request by AndreiNesterov**
Dear Daniel,

We have updated the documentation of our ontology thanks to your tool WIDOCO. The tool generated a new .htaccess file, so we would like to update it. We have commented out 'RewriteBase' (line 23) because we are not sure how to properly indicate a path. I see that in other ontologies using w3id redirection works without 'RewriteBase'. Please, let us know if we still need to correct anything in .htaccess.

Thank you!

### CODE REVIEW

**Comment by dgarijo** [comment]
@AndreiNesterov,
the files are correct, but you are serving them as GitHub links. You should serve them through something like GitHub pages. Otherwise you are serving HTML in all cases, not the respective files.
Also, you are not listed as a maintainer in this repository. Can you pls add yourself and have the PR approved by @jrvosse ?
Thanks

**Comment by jrvosse** [comment]
Hi Daniel,

Thanks for your feedback, we will work on this and than do a new PR.

Cheers, Jacco

On 16 Feb 2023, at 10:18, Daniel Garijo ***@***.***> wrote:



@AndreiNesterov<https://github.com/AndreiNesterov>,
the files are correct, but you are serving them as GitHub links. You should serve them through something like GitHub pages. Otherwise you are serving HTML in all cases, not the respective files.
Also, you are not listed as a maintainer in this repository. Can you pls add yourself and have the PR approved by @jrvosse<https://github.com/jrvosse> ?
Thanks

**Comment by AndreiNesterov** [comment]
Dear Daniel @dgarijo , 

Thank you for your quick response. We have changed the links in .htaccess to GitHub pages and added maintainers' info.

Kind regards,
Andrei

**Comment by dgarijo** [comment]
Please add yourself as a maintainer in the readme :)

**Pull request merged**
