### PR TITLE
Try 2

### PR DESCRIPTION
**Pull request by hsolbrig**

### CODE REVIEW

**Comment by cmungall** [comment]
This looks good, thanks

**Comment by cmungall** [comment]
I am the person that created the biolink record. Is there a way I can anoint @hsolbrig as a co-maintainer of this file?

**Comment by dgarijo** [comment]
Yes, just add him to the readme file as maintainer as well :)
Shall I wait for you to do another PR, or do you want me to accept this one right away?

**Comment by cmungall** [comment]
got it, made a PR for that, and yes go ahead and accept this one, many thanks!

**Comment by davidlehn** [comment]
There was an extra space in the options.  I removed it for you.

**Comment by davidlehn** [comment]
https://github.com/perma-id/w3id.org/commit/042536acdad15d6c70deca7c602a130e4276caf3

**Comment by hsolbrig** [comment]
Thanks – I’m not a mod_rewrite expert, I’m afraid

That said,   http://w3id.org/biolink/vocab/Gene  is still redirecting to https://biolink.github.io/vocab/Gene, which doesn’t make any sense given that both rewrite rules have  https://biolink.github.io/biolink-model/ as the root.  Suggestions?

**Comment by davidlehn** [comment]
Looks like the site didn't update from git.  Not sure why.  I'll look into it in an hour or so.

**Comment by davidlehn** [comment]
Should be fixed.  Unsure why that failed earlier.  It's unrelated to this particular patch.  I poked it a few times with a stick and the update finally worked.

**Pull request merged**
