### PR TITLE
Adding rules to OAIS-IP

### PR DESCRIPTION
**Pull request by mmannings**
URI namespace for [https://github.com/fengel/OAIS-IP](https://github.com/fengel/OAIS-IP) and example ontology files: [https://git.tib.eu/terminology/sandbox/oais-ip-ontology-collection/-/tree/master/dev/abox](https://git.tib.eu/terminology/sandbox/oais-ip-ontology-collection/-/tree/master/dev/abox).

### CODE REVIEW

**Comment by dgarijo** [comment]
@mmannings please remove empty htaccess.

**Comment by mmannings** [comment]
Didn't know, that they might create issues, thanks. 
Done.

**Comment by dgarijo** [comment]
No worries. In the future, only a README in the root folder is needed, unless you have different maintainers for that w3id in subfloders.
You may also avoid creating subfolders by having their path in the root htcaccess. Something like:
`^myfolder$ {http link}`

**Comment by mmannings** [comment]
Great thanks. Will maybe restructure it later, and the other project I'm maintaining here. I was also thinking of adding another rule with strict folder name inside regex, but also liked the idea of having another folder, cause it's quite convenient, even though it will make more mess in a future.

**Pull request merged**
