### PR TITLE
reworked IIoT entry

### PR DESCRIPTION
**Pull request by gatemezing**

### CODE REVIEW

**Comment by dgarijo** [comment]
@gatemezing, you are adding a duplicate  w3id here. You have IIoT and iiot. This is not accepted.

**Comment by gatemezing** [comment]
I tried to rename the previous iiot with the new IIoT. Is not possible?


"*Love all, trust a few, do wrong to none*" (W. Shakespeare)
Web: http://atemezing.org



Le ven. 18 oct. 2024 à 08:52, Daniel Garijo ***@***.***> a
écrit :

**Comment by dgarijo** [comment]
you are not renaming it, you are duplicating it

**Comment by gatemezing** [comment]
> you are not renaming it, you are duplicating it

Let me check the git option used - but it is the goal - rename old iiot to IIoT

**Comment by gatemezing** [comment]
@dgarijo - I hope it is removed now. Sorry for the confusion.

**Comment by dgarijo** [comment]
Ok, now this PR adds no changes to what we have.

**Comment by dgarijo** [comment]
@gatemezing you are changing a repo that lists Liviana Tudor as a maintainer. Can you please tell her to approve this PR?

**Comment by gatemezing** [comment]
> @gatemezing you are changing a repo that lists Liviana Tudor as a maintainer. Can you please tell her to approve this PR?

@dgarijo  - Are you know asking to have all the maintainers approving a PR? Anyway, I ping her / cc @OntoIT

**Comment by dgarijo** [comment]
No, not all maintainers. She is listed as the only maintainer.

**Comment by gatemezing** [comment]
> No, not all maintainers. She is listed as the only maintainer.

The truth is that I was helping her on this task. If you check the update, it was also coming from my fork.

**Comment by dgarijo** [comment]
Hi @gatemezing, the history of commits shows @OntoIT is the one behind all the commits: https://github.com/perma-id/w3id.org/commits/master/IIoT
You know I trust you, but it would set a bad precedent if someone who does not own a w3id or is part of the maintainer list modifies a w3id they do not own. Please have @OntoIT approve the PR and I will merge

**Comment by OntoIT** [comment]
Hi,
Please, *do not change anything* from my repository (IIoT) and w3id.com
(redirection towards my repository IIoT).
The information from that repository is under review at a journal, together
with a paper.
Please, do not let other persons from outside my repository to change my
files.
Thank you,
Liviana T.

În lun., 21 oct. 2024 la 20:29, Daniel Garijo ***@***.***> a
scris:

**Pull request closed without merging**
