### PR TITLE
Create odissei-portal

### PR DESCRIPTION
**Pull request by ritamargherita**

### CODE REVIEW

**Comment by dgarijo** [comment]
@ritamargherita this looks like a typo. Is it intended?

**Comment by ritamargherita** [comment]
Hello Daniel,

I am not sure to what exactly you’re referring. I have been trying to create a permanent ID, have I done something wrong?

Best,
Margherita


On 10 Feb 2021, at 19:27, Daniel Garijo <notifications@github.com<mailto:notifications@github.com>> wrote:



@ritamargherita<https://github.com/ritamargherita> this looks like a typo. Is it intended?

**Comment by dgarijo** [comment]
@ritamargherita,
the folder is empty, it has no redirection, so it will not work. It is also missing a reamde file.
Please see: https://github.com/perma-id/w3id.org#new and follow the instructions on how to create an identifier.
You can also use as reference one of the many identifiers that already exist in the repository.

**Comment by ritamargherita** [comment]
Alright thanks,

I have seen what happened there, and I have forked wrongly.
Thanks for letting me know.

Best,
Margherita


On 10 Feb 2021, at 19:33, Daniel Garijo <notifications@github.com<mailto:notifications@github.com>> wrote:



@ritamargherita<https://github.com/ritamargherita>,
the folder is empty, it has no redirection, so it will not work. It is also missing a reamde file.
Please see: https://github.com/perma-id/w3id.org#new and follow the instructions on how to create an identifier.
You can also use as reference one of the many identifiers that already exist in the repository.

**Comment by dgarijo** [comment]
I will close this pull request then

**Pull request closed without merging**
