### PR TITLE
Smetzger

### PR DESCRIPTION
**Pull request by stefanmet**
please consider this pull request

### CODE REVIEW

**Comment by dgarijo** [comment]
Hi @stefanmet ,
why did you change the .gitignore for the root repository?

**Comment by stefanmet** [comment]
Hi @dgarijo , I didn't want to, but couldn't update my fork before committing the .gitignore file. Could have gotten rid of it in the merge conflict, though. Let me know if it's a problem, and I'm happy to reset and do it over. Thanks!

**Comment by dgarijo** [comment]
Hi @stefanmet 
yes, it would be better if the gitignore file is not modified. I feel uncomfortable accepting changes at the root level. Thanks in advance.

**Comment by stefanmet** [comment]
Hi @dgarijo , no problem and thanks for your patience! Does this work?

**Comment by dgarijo** [comment]
@stefanmet 
It looks good to me. Do you mind adding a readme file specifying the maintainer and contact details, please? This way we can contact you in the future if any problem arises. Sorry for the inconvenience.

**Comment by stefanmet** [comment]
@dgarijo 
Sure, no problem, done. What do you think?
Thanks and later - Stefan.

**Pull request merged**
