### PR TITLE
update files

### PR DESCRIPTION
**Pull request by JYL61**
change 'https://jyl61.github.io/KMO' to 'https://jyl61.github.io/kmo'

### CODE REVIEW

**Comment by JYL61** [comment]
Hi, dgarijo. This link ‘https://jyl61.github.io/kmo' does not work. This link 'https://jyl61.github.io/KMO' is useful. 
If I want to use https://jyl61.github.io/kmo. Do I need to change the folder name KMO to lowercase kmo?

**Comment by dgarijo** [comment]
`https://jyl61.github.io/kmo` does work for me.
But your w3id is https://w3id.org/KMO right now.

**Comment by JYL61** [comment]
How do I change https://w3id.org/KMO to https://w3id.org/kmo

**Comment by dgarijo** [comment]
rename the folder :)

**Pull request merged**
