### PR TITLE
.htaccess update

### PR DESCRIPTION
**Pull request by jhaag75**
update for /xapi/medbiq

### CODE REVIEW

**Comment by davidlehn** [comment]
Can you squish these commits together to get rid of the curn?

**Comment by jhaag75** [comment]
Yes, apologies!

-------------------------------------------------------
+1.850.266.7100(office)
+1.850.471.1300 (mobile)
jhaag75 (skype)
http://jasonhaag.com (Web)
http://twitter.com/mobilejson (Twitter)
http://linkedin.com/in/jasonhaag (LinkedIn)

**Comment by davidlehn** [comment]
In case there was confusion, use rebase and force push to update this PR to avoid the unneeded commits.  Search for "git squash pull request" for various pages with instructions. Thanks.

**Comment by jhaag75** [comment]
Thanks David. Is there any easy way to do this using the browser interface?
The instructions I found are from command line:
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

I've been using the browser interface for this repo. I can switch to
command line if that's the only way. Can I simply close this pull request
for now?

-------------------------------------------------------
+1.850.266.7100(office)
+1.850.471.1300 (mobile)
jhaag75 (skype)
http://jasonhaag.com (Web)
http://twitter.com/mobilejson (Twitter)
http://linkedin.com/in/jasonhaag (LinkedIn)

**Pull request closed without merging**
