### PR TITLE
Add won folder for webofneeds project

### PR DESCRIPTION
**Pull request by fkleedorfer**

### CODE REVIEW

**Comment by dgarijo** [comment]
@fkleedorfer,
if you are not adding content negotiation, why not use just 301/302 redirect?

**Comment by fkleedorfer** [comment]
Yep you're right, I'll change it to 301. I was thinking about content negotiation, but for the time being, we won't do it.

**Comment by davidlehn** [comment]
You are welcome to use 301, but that might be cached such that a user agent wouldn't see a change on w3id.org.  Is that ok?

**Comment by fkleedorfer** [comment]
Well it sounded like a good idea at the time... but if we want to change the redirect later (e.g., add content negotiation), which we might, 301 may hide that. Not what we want, thanks for pointing that out. So I'll go for 302 then.

**Pull request merged**
