### PR TITLE
Added /ipsoeu/

### PR DESCRIPTION
**Pull request by andrea-perego**
Added redirection to the URI space of the Innovative Public Services Observatory (IPSO).

### CODE REVIEW

**Comment by dgarijo** [comment]
@andrea-perego can you please add yourself (at least) as a maintainer? It's impossible for me to know if you have any relationship with <jrc-ips@ec.europa.eu> if you change the w3id in the future

**Comment by andrea-perego** [comment]
Just done, @dgarijo . I specified the team email, since the update my be done by any team member.

**Comment by andrea-perego** [comment]
> Just done, @dgarijo . I specified the team email, since the update may be done by any team member.

Actually, thinking again about it, I wonder whether we'd better refer to https://github.com/ipsoeu as maintainer, as this refers to the GH organisation from which possible PRs will be created to update the ipsoeu w3id.

**Comment by dgarijo** [comment]
You may add as many maintainers as you want. But the maintainer has to be someone who I can verify when doing the pull requests.

**Comment by andrea-perego** [comment]
> You may add as many maintainers as you want. But the maintainer has to be someone who I can verify when doing the pull requests.

Got it, thanks.

**Comment by dgarijo** [comment]
no problem!

**Pull request merged**
