### PR TITLE
content description ontology cdesc

### PR DESCRIPTION
**Pull request by andresgs77**
Redirecting to the content description ontology

### CODE REVIEW

**Comment by dgarijo** [comment]
Please, add a readme file indicating the maintainer of the redirection. For example: https://github.com/perma-id/w3id.org/tree/master/bibma

A few comments:
1) The URI of your ontology is : http://w3id.org/contentdesc#. You are creating the redirection of http://w3id.org/cdesc. If you try to resolve http://w3id.org/contentdesc with the current htaccess, you will get a 404. 

2) Your ontology uses http instead of https. This will work because w3id redirects http to https, but I have experienced some problems in the past when loading the ontology in Protege this way. I suggest changing the URI to https (https://w3id.org/cdesc).

**Comment by andresgs77** [comment]
Yes, I was going to revert the pull request when I realised that the ontology name does not correspond to what I define in w3id but you were faster than me.

**Comment by dgarijo** [comment]
Note that you haven't changed the URI of the ontology in the term documentation (e.g. http://w3id.org/contentdesc#Concept)

**Comment by andresgs77** [comment]
yes I have, it should be the cache.

**Pull request merged**
