### PR TITLE
Adding uh-linked-data

### PR DESCRIPTION
**Pull request by natuk**
Adding a `.htaccess` file and `README.md` file for redirection of url to the letterlocking.org website where a vocabulary of terms is being shared.

### CODE REVIEW

**Comment by dgarijo** [comment]
@natuk,
you are creating a w3id for which you will not be a maintainer. Can you please add yourself as a maintainer too?  I ask just in case you want to submit updates.

**Comment by natuk** [comment]
Thanks for picking this up @dgarijo . Do you mean as in a maintainer of the forked repository? I am only a contributor, but I can ask the maintainer to make me a maintainer as well, if this is what you mean.

**Comment by davidlehn** [comment]
@natuk The README.md contact/maintainer list should list github ids of those who are allowed to update the files in this dir.

**Comment by natuk** [comment]
I see, I have added a reference to my account and email in the README file now. Please check that this is OK.

**Pull request merged**
