### PR TITLE
New htaccess for Progetto Irnerio (Irnerio Project)

### PR DESCRIPTION
**Pull request by essepuntato**
**Name of the project:** Progetto Irnerio

**Description:** The core part of this project consists of digitizing and classifying the vast collection of legal and theological-philosophical codices making up the rare-books collection of the Reale Collegio di Spagna in Bologna: with this digital catalogue, built under the guidance of Professors Domenico Maffei and Andrea Padovani, not only can the fragile codices be readily accessed and studied, but their preservation for future use is guaranteed, too. The project - named for the primus illuminator of legal science studies in Bologna, the Italian jurist Irnerius - have been possible by the Collegio di Spagna that made its rare-books collection available. Funding for the project comes from the Fondazione Cassa di Risparmio in Bologna, and also from the Italian Ministry of Higher Education and Scientific Research. The digital images have been reproduced under the editorship of the publishing house CLUEB. 

**Contacts:**
* Monica Palmirani <monica.palmirani@unibo.it>
* Silvio Peroni <silvio.peroni@unibo.it>

### CODE REVIEW

**Comment by dgarijo** [comment]
@essepuntato,
could you please add a separate readme file with the description and maintainers of the project?

**Comment by davidlehn** [comment]
@dgarijo I think the .htaccess comment contact info is enough.  Less files to deal with.  Though maybe we should encourage people to add the github user names too so it's easier to track who can update files.

**Comment by dgarijo** [comment]
@davidlehn,
I think we should have the same guidelines for everyone. Having a description in the .htaccess is fine, but what if they add subdirectories with .htaccess? Would  they have to add the description and maintainers in all of them? I think that a readme on the parent folder makes more sense. Also, I agree on providing github names for contributors :)

**Comment by essepuntato** [comment]
Hi guys,

I will add the readme if necessary at this stage — just let me know. 

However, please, update the guidelines in the w3id.org Website, since they state “add contact info in a README **or** .htaccess comment”.

Have a nice day :-)

S

**Comment by essepuntato** [comment]
Added the README.md as requested

**Pull request merged**
