### PR TITLE
New .htaccess

### PR DESCRIPTION
**Pull request by essepuntato**
This permanent ID has been created for providing a space for all the resources associated to AkomaNtoso, i.e. a set of simple technology-neutral electronic representations in XML format of parliamentary, legislative and judiciary documents, available at http://www.akomantoso.org/.

### CODE REVIEW

**Comment by essepuntato** [comment]
Hi @dgarijo,

I've just forgot to add contact information to the .htaccess, i.e. my email address and the link to the main AkomaNtoso page.

I'll do that once the push request will be accepted, is that fine?

**Comment by dgarijo** [comment]
Hi @essepuntato,
please do add the readme file before we accepts the pull request. It is what we have been doing with everyone else.
Thanks in advance.

**Comment by essepuntato** [comment]
Hi @dgarijo,

I've just done it again as a new pull request, since I've noticed that also another project of mine was not already included in the official w3id.org redirection mechanism.

The new pull request is https://github.com/perma-id/w3id.org/pull/580.

**Comment by dgarijo** [comment]
Ok, I merged it :)

**Pull request closed without merging**
