### PR TITLE
Create .htaccess at perma-id/w3id.org in OntoDocRel folder

### PR DESCRIPTION
**Pull request by QamarPC103006**
.htaccess file for publishing OntoDocRel ontology in OntoDocRel folder at perma-id/w3id.org

### CODE REVIEW

**Comment by davidlehn** [comment]
You might want to add the README.md from #499 here as OntoDocRel/README.md.

Also note the final URLs created by this are https://w3id.org/OntoDocRel/ontodocrel.  Did you mean for the redirect to just be just https://w3id.org/OntoDocRel?

**Comment by QamarPC103006** [comment]
Yes, both requests #499 and #501 are for same task  i.e. to publish OntoDocRel ontology on w3id.org

Yes, README.md file from OntoDocRel is required to be added for this request.
Actually I am new to use w3id.org service, so I was confused during this configuration process

Also it will be desirable that redirect should be to https://w3id.org/OntoDocRel/

**Comment by QamarPC103006** [comment]
Can you please update me regarding the publishing of OntoDocRel. Please let
me know if any update/placement of some file is required at my end for
completion of this configuration

**Comment by dgarijo** [comment]
@QamarPC103006 
Yes, you can do something on your end:
1) Please close one of the pull requests you have open. You seem to have created 2 for the same purpose.
2) As @davidlehn pointed out, you are currently redirecting https://w3id.org/OntoDocRel/ontodocrel to your URI. If you want to redirect https://w3id.org/OntoDocRel, then replace ^ontodocrel$ with ^$

**Comment by QamarPC103006** [comment]
Thanks for guideline

1) I have closed pull request # 499 and just request #501 is opened for
performing this config.
2) I have updated .htaccess file in my local repository as guided.

**Comment by dgarijo** [comment]
@QamarPC103006 Please add a readme file indicating the contact details and a brief description of the resource. We need this for maintainability purposes.

**Pull request merged**
