### PR TITLE
Update idsa redirects to include versioning

### PR DESCRIPTION
**Pull request by JohannesLipp**
@clange FYI

### CODE REVIEW

**Comment by JohannesLipp** [comment]
The interesting part for the versioning is at https://github.com/perma-id/w3id.org/pull/2226/files#diff-61f7134f53f168b90d58c9825d5a3c86f9c8b38968596166a175bd7fa330e7bcR24

**Comment by dgarijo** [comment]
@JohannesLipp,
you are adding yourself as a contributor to a repo you did not create. Please have @clange, @sebbader or @HaydarAk approve your request.

**Comment by JohannesLipp** [comment]
> @JohannesLipp,
> you are adding yourself as a contributor to a repo you did not create. Please have @clange, @sebbader or @HaydarAk approve your request.

Thank you for the hint! I requested approval from my colleagues right now.

**Comment by sebbader** [comment]
Hello @dgarijo, I can hereby confirm that @JohannesLipp is a contributor of our project.

**Pull request merged**
