### PR TITLE
Updates to openbadges

### PR DESCRIPTION
**Pull request by xaviaracil**
This updates:
- Contact information
- Redirection to Open Badges v2.0 JSON-LD context file

### CODE REVIEW

**Comment by dgarijo** [comment]
@xaviaracil please have  Markus Gylling <mgylling@imsglobal.org> (the main contact for curating this w3id) approve this PR.

Last push was done by @ottonomy

**Comment by xaviaracil** [comment]
@dgarijo I'm afraid Markus no longer works at 1EdTech, so I don't have his contact. Can @ottonomy approve it?

**Comment by dgarijo** [comment]
Yes, please have @ottonomy approve it.
And also, please add either @ottonomy and yourself as maintainers.

**Comment by justinpitcher** [comment]
Just for visibility, I am confirming that Xavi is the correct contact and we should approve this change. Hopefully this gets fixed today as it is breaking OB 2 validation workflows.

**Comment by dgarijo** [comment]
This is why we ask for maintainers in a w3id. 

The current listed maintainer is Markus Gylling [mgylling@imsglobal.org](mailto:mgylling@imsglobal.org). @ottonomy did the last changes, and therefore I think it's ok for him/her to approve the PR. 

You are changing both the domain and the maintainer in this PR, so unless a previous maintainer or committer approves the PR, I don't think we should merge it. I can't verify if this is an attempt to take ownership over someone else's w3id.

Also, please update the maintainers in the PR with the new maintainer list.

**Comment by justinpitcher** [comment]
Thankfully Nate is still very much involved with the group and will eventually see this.

@xaviaracil perhaps you should add Rob and any other 1EdTech people you think of. We could add the DC chairs but that's a rotating group in theory.

**Comment by xaviaracil** [comment]
I've added Rob as a contact and our support team as a maintainer, so we won't have to deal with this contact issue anymore.

@dgarijo Regarding the domain change, we changed from imsglobal.org to 1edtech.org a couple of years ago.

**Comment by dgarijo** [comment]
Ok, given that https://www.imsglobal.org/activity/digital-credentialing-badges redirects to https://www.1edtech.org/standards/open-badges, I will merge this PR.

**Comment by ottonomy** [comment]
Thanks, all!

@xaviaracil and Rob Coyle are indeed the correct current maintainers for Open Badges, which is a 1EdTech (formerly IMS Global) specification.

**Pull request merged**
