### PR TITLE
UnderRepresentedWriters Project

### PR DESCRIPTION
**Pull request by marcostranisci**
Permanent Identifier request for the Under-Represented Writers Project

### CODE REVIEW

**Comment by dgarijo** [comment]
@marcostranisci,
sorry, we don't host ontologies in this repo. This is only for the redirections. See https://github.com/perma-id/w3id.org/tree/master/example for an example redirection

**Comment by marcostranisci** [comment]
You're right, sorry! I removed the Ontology and left only the url, and my mail as a mantainer

**Comment by dgarijo** [comment]
But now you don't have an htaccess, so you are not redirecting to anything... Please have a look at the example I pointed to for a reference.

**Comment by marcostranisci** [comment]
You're right again. I chose to follow the examples from generic Github pages since the ontology is only a part of my whole project. Thanks for your help

**Comment by davidlehn** [comment]
@dgarijo This should have been squashed to avoid the 6MB 135000 line file in git history.  I'd like to be evil and force push a fix for that, but master branch is protected at the moment and I'm not an admin.  I'm requesting assistance on that.  Trying to do it before other PRs are merged.

@marcostranisci If a squash of your commits is pushed, you'll need to re-checkout before making new changes.

**Comment by dgarijo** [comment]
Apologies, @davidlehn

**Pull request merged**
