### PR TITLE
ADD asbing 

### PR DESCRIPTION
**Pull request by AnneGoebels**
redirection for ASB-ING Ontology

### CODE REVIEW

**Comment by dgarijo** [comment]
@AnneGoebels,
you are feferring to documents which are not in the current repository. You should replace  things like 
```
RewriteRule ^$ index-en.html [R=303,L]
```
with the URL of the server hosting that file.
See https://github.com/perma-id/w3id.org/blob/master/example/.htaccess
for an example

**Comment by davidlehn** [comment]
@dgarijo I think `RewriteBase` will take care of that?

@AnneGoebels You have your base set to the github UI URLs.  You probably want to point at a github pages site or other place where the raw files are hosted.

**Comment by dgarijo** [comment]
True, my bad, i skipped to the redirection section without seeing the rewrite base!

**Comment by AnneGoebels** [comment]
@davidlehn true, sorry, I will change the base URI to a github pages site

**Pull request merged**
