### PR TITLE
the DBA ontology

### PR DESCRIPTION
**Pull request by oibaf**

### CODE REVIEW

**Comment by dgarijo** [comment]
@oibaf,
please add yourself as a maintainer so if there are future updates to the w3id I can verify it's you.

**Comment by oibaf** [comment]
@dgarijo,
please help me understand your request, are you talking about github roles? actually the pull request is not from a repository owned by an organization, I am acting on behalf of an organization and the owner of the clone will change in the future

sorry but I am not skilled on github

thanks!

**Comment by dgarijo** [comment]
@oibaf 
In the readme file, add yourself, (i.e., name and email or GitHUb user id) as a maintainer (you can add more people too). That way, if someone else attempts to change your w3id, I will know whether they are allowed or not

**Comment by oibaf** [comment]
@dgarijo,

very clear, sorry I took the wrong way, thank you

**Pull request merged**
