### PR TITLE
Bootstrap 3 (fixing layout issues on mobile devices such as iPhone 5)

### PR DESCRIPTION
**Pull request by AlexanderWillner**

### CODE REVIEW

**Comment by msporny** [comment]
Thanks for the patch @AlexanderWillner!

**Comment by davidlehn** [comment]
@AlexanderWillner That other "federation sub ontology" commit was supposed to happen too right?

**Comment by AlexanderWillner** [comment]
Well, was supposed to happen in general, so no issue that it has been pushed - but it doesn't really belong to the Bootstrap update of course.

**Comment by davidlehn** [comment]
It got lumped in the pull, but the commit isn't really connected.  Just making sure it didn't slip in by mistake.

**Pull request merged**
