### PR TITLE
Add /cwl for Common Workflow Language

### PR DESCRIPTION
**Pull request by stain**
See https://common-workflow-language.github.io/

(not sure if the .htaccess is quite right, but let's see what Travis says :-) )

### CODE REVIEW

**Comment by msporny** [comment]
Squash the commits please, and then we'll pull.

**Comment by stain** [comment]
My apologies.. squash commit coming up.

**Comment by stain** [comment]
Like this..? :-)

**Comment by msporny** [comment]
Yep, thanks :). Merged.

**Comment by stain** [comment]
Thanks from the [BOSC 2015 Codefest](http://www.open-bio.org/wiki/Codefest_2015)!

**Pull request merged**
