### PR TITLE
CREATE .htaccess

### PR DESCRIPTION
**Pull request by ghost**
Would like  w3id.org/SCL to redirect to  https://www.qualtrics.com/
Did I create the correct file and use the correct code?

### CODE REVIEW

**Comment by davidlehn** [comment]
Are these survey links intended to be long lived?  As in something that needs to work for years or even decades.  I'm wondering if perhaps a traditional URL shortener service would be more appropriate for your use case.

**Comment by courtneykase** [comment]
They are not going to live long.  Very good point you make  Do you have recommendation like google url shortener or other?

**Comment by davidlehn** [comment]
I rarely have the need to shorten urls.  The classic https://tinyurl.com/ lets you pick an alias.  https://goo.gl/, https://bitly.com/, and others have stats and commercial features.  Not hard to try them all.

**Comment by davidlehn** [comment]
New commits removed all changes? Closing. Reopen if needed.

**Pull request closed without merging**
