### PR TITLE
Create htaccess

### PR DESCRIPTION
**Pull request by marco-medici**
added agrochemicals-ontology redirect

### CODE REVIEW

**Comment by davidlehn** [comment]
File name was incorrect, fixed in https://github.com/perma-id/w3id.org/pull/2209.

**Comment by davidlehn** [comment]
@marco-medici Looks like this `.htaccess` probably doesn't do what you want.  The bare dir doesn't redir at all and if you add a path component, it goes to `.../agrochemicals_T.ttl/xxx`  Please fix, test, and submit a change.

**Comment by marco-medici** [comment]
I am sorry for these mistakes. Thank you all for your precious support, I'm not so familiar with these tools.

**Comment by marco-medici** [comment]
@davidlehn, @dgarijo what could I do now to obtain a IRI for this file?
https://github.com/marco-medici/agrochemicals-ontology/blob/main/agrochemicals_T.ttl

**Comment by dgarijo** [comment]
Publish it as a Github page, and you will receive accessible URLs to all the files in your repository. I do this all the time. More info: https://pages.github.com/

**Comment by marco-medici** [comment]
> 
> 
> Publish it as a Github page, and you will receive accessible URLs to all the files in your repository. I do this all the time. More info: https://pages.github.com/

Hope now it works...

**Comment by dgarijo** [comment]
You'll have to submit a new pull request with the new URL

**Comment by marco-medici** [comment]
You mean that I should update the sample URL in the ttl file with this one? 
https://github.com/marco-medici/agrochemicals-ontology/blob/main/agrochemicals_T.ttl

**Comment by dgarijo** [comment]
If you follow the steps in https://pages.github.com/, then you'll be able to generate a URL like marco-medici.github.io/agrochemicals-ontology/agrochemicals_T.ttl. And then you should use that URL in a new pull request replacing the current link.

**Comment by marco-medici** [comment]
I've created the new repository github.com/marco-medici/marco-medici.github.io and replaced the URL http://www.marco-medici.github.io/agrochemicals-ontology/agrochemicals_T.ttl in the ttl file...

**Pull request merged**
