### PR TITLE
Revert "added NE and P flags to rewrite"

### PR DESCRIPTION
**Pull request by zednis**
Reverts perma-id/w3id.org#135

pull request did not have the desired effects.  Please revert.  Thank you.

### CODE REVIEW

**Comment by zednis** [comment]
Thanks.

**Comment by davidlehn** [comment]
What effect are you trying to do?

**Comment by zednis** [comment]
I would like to change the redirect to a proxy so the w3id.org URL is preserved when the user loads the webpage in a browser and the nocv.tw.rpi.edu source is not necessarily visible.

https://w3id.org/national-ocean-council/api/ -> https://nocv.tw.rpi.edu/elda/api/

**Comment by davidlehn** [comment]
w3id.org doesn't work as a full proxy at this time, sorry.  That would require more infrastructure and resources than we have in place now.  It is annoying that the URL will change in browsers so if that's important you may need to look into other services.  For use cases where the URL isn't exposed in the UI the redirect works well.

**Pull request merged**
