### PR TITLE
Update of .htaccess

### PR DESCRIPTION
**Pull request by anuzzolese**
Request to enable permanent URLs for stlab.

### CODE REVIEW

**Comment by dgarijo** [comment]
This branch has conflicts with the main branch. Please solve the conflicts, otherwise I cannot merge

**Comment by dgarijo** [comment]
The url http://150.146.207.10 does not seem stable. Can you please move it to some stable URL?

**Comment by anuzzolese** [comment]
Hi @dgarijo,

what's the problem with such an URL?

**Comment by dgarijo** [comment]
The URL resolves, but it's a fragile setup. We recommend having the URLs using DNS in order to avoid constant updates to w3ids.

**Comment by dgarijo** [comment]
@anuzzolese, did you have the chance to look at the DNS thing? I don't want to be a blocker, but it is better for the maintenance of the repo. If you can't find a proper place, I could merge the branch...

**Comment by anuzzolese** [comment]
@dgarijo I changed the target URL.

**Pull request merged**
