### PR TITLE
Add Open Badges spec and context, incorporating legacy v1 context

### PR DESCRIPTION
**Pull request by ottonomy**
The change to the ./v1 redirect here incorporates the previous version and has been tested by @dlongley . These updates should be ready to go. We'll follow up shortly to update these to HTTPS.

### CODE REVIEW

**Comment by ottonomy** [comment]
Hold off at least a day on this -- The continuous integration on our specification website didn't grab my latest changes that would make this usable. I'll update when it's ready to merge.

**Comment by ottonomy** [comment]
This PR has been updated, and https://openbadgespec.org is live and ready for redirection. Let me know if you have any questions.

**Comment by dlongley** [comment]
@ottonomy,

There are typos in the JSON-LD context (https://openbadgespec.org/v1/context.json):

```json
    "uid": { "@id": "obi:uid", "type": "xsd:string" },
    "recipient": { "@id": "obi:recipient", "type": "@id" },
    "hashed": { "@id": "obi:hashed", "type": "xsd:boolean" }
```

`"type"` should be `"@type"`. I recommend running a few examples through the [JSON-LD playground](http://json-ld.org/playground) with that example context (minus the legacy context which won't work until this PR is merged) to make sure things look right.

**Comment by ottonomy** [comment]
Dave, the `@type` bug has been fixed: https://openbadgespec.org/v1/context.json

**Pull request merged**
