### PR TITLE
Add redirect to vaccination certificates interop report.

### PR DESCRIPTION
**Pull request by msporny**

### CODE REVIEW

**Comment by dgarijo** [comment]
@msporny, could you please add a readme with the maintainers for this repo? Las update was done by @tplooker and I cannot verify whether you own this w3id. Thanks in advance.

**Comment by tplooker** [comment]
@dgarijo I cant write to this branch but just wanted to leave a comment in case it is unclear that I'm happy for @msporny to be a co-owner.

**Comment by msporny** [comment]
> @msporny, could you please add a readme with the maintainers for this repo? Las update was done by @tplooker and I cannot verify whether you own this w3id. Thanks in advance.

Done.

**Comment by dgarijo** [comment]
Thx!

**Pull request merged**
