### PR TITLE
creation of a new redirect entry for MICA ontologies

### PR DESCRIPTION
**Pull request by gloucklegnou**

### CODE REVIEW

**Comment by dgarijo** [comment]
The PR seems to be right, but just one comment: you are creating w3id.org/mica/ontology/domain, not w3id.org/mica/ontology/domainOntology, as you point out in the readme file. Please acknowledge this before merging

**Comment by gloucklegnou** [comment]
Ontology name has been corrected to be consitent with rewriting rules

**Comment by gloucklegnou** [comment]
Le 01/07/2016 15:36, Daniel Garijo a écrit :
>
> The PR seems to be right, but just one comment: you are creating 
> w3id.org/mica/ontology/domain, not 
> w3id.org/mica/ontology/domainOntology, as you point out in the readme 
> file. Please acknowledge this before merging
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/perma-id/w3id.org/pull/458#issuecomment-229948347>, or 
> mute the thread 
> <https://github.com/notifications/unsubscribe/AHJGPBg7wUJHHyXrkMyG3W2Td5ow3zZuks5qRRfvgaJpZM4JDIY8>.
>
you're right
I've corrected the readme file and pushed it on my w3id.org repository.

I'm not so fluent wih github... do I need to issue an other pull request ?

thanks

Philippe

-- 
Philippe Genoud
Universite Grenoble Alpes
-------------------------------------------------------
STEAMER group
Laboratoire d'Informatique de Grenoble (LIG)
Bâtiment IMAG
700 avenue Centrale
Domaine Universitaire - 38401 St Martin d'Hères
-------------------------------------------------------
adresse postale
LIG - Bâtiment IMAG - CS 40700 - 38058 GRENOBLE CEDEX 9
-------------------------------------------------------
Tel: tel: (+33) (0)4 57 42 15 01

**Comment by dgarijo** [comment]
No you don't :)

**Pull request merged**
