### PR TITLE
conceptual mapping ontology

### PR DESCRIPTION
**Pull request by dachafra**

### CODE REVIEW

**Comment by dgarijo** [comment]
@dachafra,
please add a readme file indicating the maintainer of the repo, as per the guidelines: https://github.com/perma-id/w3id.org#suitable-pr-content

**Comment by dachafra** [comment]
done! @dgarijo

**Comment by dgarijo** [comment]
@dachafra,
you are not adding yourself as a maintainer. That means that future commits will have to be approved by  @anaigmo . Is this intended or did you forget to add yourself?

**Comment by dachafra** [comment]
Sorry, I didn't know that several maintainers were allowed. Thanks @dgarijo !

**Pull request merged**
