### PR TITLE
update contacts

### PR DESCRIPTION
**Pull request by maxraupach**

### CODE REVIEW

**Comment by maxraupach** [comment]
i have a question, wenn i try the redirect link: `https://w3id.org/GerPS-onto/ontology`, it didnt work. Will it be unlock, or is the .htaccess broken?

**Comment by dgarijo** [comment]
Your w3id is http://w3id.org/GerPS-Ontology, so that's the one that works

**Comment by maxraupach** [comment]
oh ok! how can i change it?

**Comment by dgarijo** [comment]
You have to rename the folder to exactly what you want your w3id to be.
You named your folder `GerPS-Ontology` and hence that's the w3id you got.
If you rename your folder to `GerPS-onto` and in the htaccess you add the redirection for `ontology`, it should work

**Comment by maxraupach** [comment]
ty very much =)

**Pull request merged**
